import type { Word } from '../types.js';

/**
 * MIL1 — Naujokas / Recruit.
 *
 * The first day in a Lithuanian military environment: the sounds that trip up
 * English speakers, how to address a superior, how to report in, the handful of
 * commands you will hear within your first hour, and digits 0–9 for grids and
 * radio traffic.
 *
 * Citation forms follow the Dabartinės lietuvių kalbos žodynas convention.
 * Commands are given in the imperative — the form actually shouted on a parade
 * ground — not in the infinitive. See docs/LINGUISTIC_NOTES.md.
 */
export const mil1Words: Word[] = [
  // ── Sounds that matter on the radio ───────────────────────────────────────
  {
    lt: 'š',
    en: 'the letter “š” (sh as in “ship”)',
    pron: 'sh',
    pos: 'letter',
    level: 'MIL1',
    category: 'sounds',
    emoji: '🔤',
    usage: 'Appears in “šautuvas” (rifle) and “šalmas” (helmet) — two words you will hear daily.',
    examples: [{ lt: 'šautuvas', en: 'a rifle' }],
  },
  {
    lt: 'ž',
    en: 'the letter “ž” (zh as in “measure”)',
    pron: 'zh',
    pos: 'letter',
    level: 'MIL1',
    category: 'sounds',
    emoji: '🔤',
    usage: 'In “žemėlapis” (map) and “žengte marš” (forward march).',
    examples: [{ lt: 'žemėlapis', en: 'a map' }],
  },
  {
    lt: 'č',
    en: 'the letter “č” (ch as in “church”)',
    pron: 'ch',
    pos: 'letter',
    level: 'MIL1',
    category: 'sounds',
    emoji: '🔤',
    examples: [{ lt: 'ačiū', en: 'thank you' }],
  },
  {
    lt: 'ė',
    en: 'the letter “ė” (a tight “ay” with no glide)',
    pron: 'ay',
    pos: 'letter',
    level: 'MIL1',
    category: 'sounds',
    emoji: '🔤',
    grammar: 'Always long, never interchangeable with e. “Dėmesio” ≠ “demesio”.',
    examples: [{ lt: 'dėmesio', en: 'attention' }],
  },
  {
    lt: 'j',
    en: 'the letter “j” (y as in “yes”)',
    pron: 'y',
    pos: 'letter',
    level: 'MIL1',
    category: 'sounds',
    emoji: '🔤',
    grammar: 'Lithuanian “y” is a long vowel [iː], never a consonant.',
    examples: [{ lt: 'jūs', en: 'you (plural / polite)' }],
  },
  {
    lt: 'ū',
    en: 'the letter “ū” (a long oo)',
    pron: 'oo (long)',
    pos: 'letter',
    level: 'MIL1',
    category: 'sounds',
    emoji: '🔤',
    examples: [{ lt: 'būrys', en: 'a platoon' }],
  },

  // ── Address & courtesy ────────────────────────────────────────────────────
  {
    lt: 'ponas',
    en: 'sir; Mr',
    pron: 'POH-nahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL1',
    category: 'address',
    emoji: '🎖️',
    grammar:
      'Address form (vocative): “pone”. Lithuanian puts the rank into the vocative too: pone kapitone, pone leitenante, pone puskarininki.',
    usage:
      'Standard way to address a superior in the Lithuanian Armed Forces: “pone” + rank, both in the vocative.',
    examples: [{ lt: 'Taip, pone kapitone!', en: 'Yes, sir! (to a captain)' }],
  },
  {
    lt: 'ponia',
    en: 'ma’am; Mrs',
    pron: 'POH-nyah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL1',
    category: 'address',
    emoji: '🎖️',
    grammar: 'Vocative is identical: “ponia”. Rank still takes the vocative: “ponia kapitone”.',
    examples: [{ lt: 'Supratau, ponia majore!', en: 'Understood, ma’am! (to a major)' }],
  },
  {
    lt: 'taip',
    en: 'yes',
    pron: 'tighp',
    pos: 'particle',
    level: 'MIL1',
    category: 'address',
    emoji: '✅',
    usage: 'Rarely stands alone to a superior — add the rank: “Taip, pone puskarininki!”',
    examples: [{ lt: 'Taip, pone puskarininki!', en: 'Yes, sergeant!' }],
  },
  {
    lt: 'ne',
    en: 'no; not',
    pron: 'neh',
    pos: 'particle',
    level: 'MIL1',
    category: 'address',
    emoji: '❌',
    grammar:
      'As a negator it fuses with the verb: ne + suprantu → “nesuprantu” (I don’t understand).',
    examples: [{ lt: 'Ne, pone leitenante.', en: 'No, lieutenant.' }],
  },
  {
    lt: 'klausau',
    en: 'yes? ; I’m listening; at your command',
    pron: 'klow-SOW',
    pos: 'verb',
    level: 'MIL1',
    category: 'address',
    emoji: '👂',
    grammar: '1st person of “klausyti” (to listen).',
    usage:
      'The standard response when a superior calls your name, and the standard way to answer a field telephone.',
    examples: [{ lt: '— Eilini Smitai! — Klausau!', en: '— Private Smith! — Sir!' }],
  },
  {
    lt: 'supratau',
    en: 'understood; roger',
    pron: 'soo-prah-TOW',
    pos: 'verb',
    level: 'MIL1',
    category: 'address',
    emoji: '👍',
    grammar: 'Past tense of “suprasti” — literally “I understood”.',
    usage: 'Acknowledges an order or a radio message. Pairs with “Vykdau!” when you act on it.',
    tags: ['radio'],
    examples: [{ lt: 'Supratau, pone kapitone!', en: 'Understood, captain!' }],
  },
  {
    lt: 'vykdau',
    en: 'executing; carrying it out; wilco',
    pron: 'VEEK-dow',
    pos: 'verb',
    level: 'MIL1',
    category: 'address',
    emoji: '🏃',
    grammar: '1st person of “vykdyti” (to carry out, to execute).',
    usage: 'Says you have understood *and* are complying. “Įvykdyta!” = task complete.',
    tags: ['radio'],
    examples: [{ lt: 'Vykdau, pone vade!', en: 'Carrying it out, commander!' }],
  },
  {
    lt: 'leiskite kreiptis',
    en: 'permission to speak (lit. “allow me to address you”)',
    pron: 'LAYS-kee-teh KRAYP-tis',
    pos: 'phrase',
    level: 'MIL1',
    category: 'address',
    emoji: '🙋',
    grammar: 'Polite plural imperative of “leisti” (to allow) + “kreiptis” (to address).',
    usage: 'The formal way to open a conversation with a superior.',
    examples: [{ lt: 'Leiskite kreiptis, pone kapitone!', en: 'Permission to speak, captain!' }],
  },
  {
    lt: 'nesuprantu',
    en: 'I don’t understand',
    pron: 'neh-soo-PRAHN-too',
    pos: 'phrase',
    level: 'MIL1',
    category: 'address',
    emoji: '🤷',
    usage:
      'Better to say this immediately than to guess at an order. Follow with “Pakartokite, prašau.”',
    examples: [{ lt: 'Atsiprašau, nesuprantu.', en: 'Sorry, I don’t understand.' }],
  },
  {
    lt: 'pakartokite',
    en: 'repeat; say again',
    pron: 'pah-kahr-TOH-kee-teh',
    pos: 'command',
    level: 'MIL1',
    category: 'address',
    emoji: '🔁',
    grammar: 'Polite plural imperative of “pakartoti”. Informal singular: “pakartok”.',
    usage:
      'On the radio this is the standard request for a retransmission. Note that English “repeat” is a fire-support term — Lithuanian “pakartokite” carries no such risk.',
    tags: ['radio'],
    examples: [{ lt: 'Pakartokite, prastas ryšys.', en: 'Say again, poor comms.' }],
  },
  {
    lt: 'lėčiau',
    en: 'slower',
    pron: 'LAY-chow',
    pos: 'adverb',
    level: 'MIL1',
    category: 'address',
    emoji: '🐢',
    grammar: 'Comparative of “lėtai” (slowly).',
    examples: [{ lt: 'Kalbėkite lėčiau, prašau.', en: 'Please speak more slowly.' }],
  },
  {
    lt: 'ačiū',
    en: 'thank you',
    pron: 'AH-choo',
    pos: 'interjection',
    level: 'MIL1',
    category: 'address',
    emoji: '🙏',
    examples: [{ lt: 'Ačiū, pone puskarininki.', en: 'Thank you, sergeant.' }],
  },
  {
    lt: 'atsiprašau',
    en: 'sorry; excuse me',
    pron: 'aht-see-prah-SHOW',
    pos: 'phrase',
    level: 'MIL1',
    category: 'address',
    emoji: '😔',
    grammar: 'Literally “I apologise”. Formal plural: “atsiprašome”.',
    examples: [{ lt: 'Atsiprašau, pone kapitone.', en: 'My apologies, captain.' }],
  },
  {
    lt: 'laba diena',
    en: 'good afternoon; good day',
    pron: 'LAH-bah DYEH-nah',
    pos: 'phrase',
    level: 'MIL1',
    category: 'address',
    emoji: '🌤️',
    usage: 'The neutral, always-safe greeting to Lithuanian personnel of any rank.',
    examples: [{ lt: 'Laba diena, pone majore.', en: 'Good afternoon, major.' }],
  },

  // ── Reporting in ──────────────────────────────────────────────────────────
  {
    lt: 'atvykau',
    en: 'I have arrived; reporting',
    pron: 'aht-vee-KOW',
    pos: 'verb',
    level: 'MIL1',
    category: 'reporting',
    emoji: '🫡',
    grammar: 'Past tense of “atvykti” (to arrive).',
    usage:
      'The core of reporting in: rank + surname + “pagal jūsų įsakymą atvykau” (reporting as ordered).',
    examples: [
      {
        lt: 'Eilinis Smitas pagal jūsų įsakymą atvyko!',
        en: 'Private Smith reporting as ordered!',
      },
    ],
  },
  {
    lt: 'įsakymas',
    en: 'order; command',
    pron: 'EE-sah-kee-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL1',
    category: 'reporting',
    emoji: '📋',
    grammar: 'From “įsakyti” (to order). “Pagal jūsų įsakymą” = as per your order.',
    examples: [{ lt: 'Įsakymas aiškus.', en: 'The order is clear.' }],
  },
  {
    lt: 'aišku',
    en: 'clear; understood',
    pron: 'IGHSH-koo',
    pos: 'adverb',
    level: 'MIL1',
    category: 'reporting',
    emoji: '💡',
    usage: 'A commander ends a brief with “Aišku?” — you answer “Aišku!”',
    examples: [{ lt: '— Aišku? — Aišku, pone vade!', en: '— Clear? — Clear, commander!' }],
  },
  {
    lt: 'pasiruošęs',
    en: 'ready',
    pron: 'pah-see-RWOH-shays',
    pos: 'adjective',
    level: 'MIL1',
    category: 'reporting',
    emoji: '✅',
    grammar: 'Past active participle of “pasiruošti”. Feminine “pasiruošusi”, plural “pasiruošę”.',
    alt: ['pasiruošusi', 'pasiruošę'],
    examples: [{ lt: 'Skyrius pasiruošęs!', en: 'The section is ready!' }],
  },
  {
    lt: 'karys',
    en: 'soldier; serviceman',
    pron: 'kah-REES',
    pos: 'noun',
    gender: 'm',
    level: 'MIL1',
    category: 'people',
    emoji: '🪖',
    grammar: 'The general, respectful term. Plural “kariai”. Feminine “karė” is used but rarer.',
    examples: [
      { lt: 'Lietuvos kariuomenės karys.', en: 'A soldier of the Lithuanian Armed Forces.' },
    ],
  },
  {
    lt: 'vadas',
    en: 'commander; leader',
    pron: 'VAH-dahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL1',
    category: 'people',
    emoji: '⭐',
    grammar: 'Vocative “vade”. “Būrio vadas” = platoon commander.',
    examples: [
      { lt: 'Skyriaus vadas duoda įsakymą.', en: 'The section commander gives the order.' },
    ],
  },
  {
    lt: 'kariuomenė',
    en: 'the armed forces; the army',
    pron: 'kah-ryoo-OH-meh-nay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL1',
    category: 'people',
    emoji: '🇱🇹',
    grammar: '“Lietuvos kariuomenė” — the Lithuanian Armed Forces.',
    examples: [
      { lt: 'Tarnauju Lietuvos kariuomenėje.', en: 'I serve in the Lithuanian Armed Forces.' },
    ],
  },
  {
    lt: 'kareivinės',
    en: 'barracks',
    pron: 'kah-RAY-vee-nays',
    pos: 'noun',
    gender: 'f',
    level: 'MIL1',
    category: 'places',
    emoji: '🏚️',
    grammar: 'Plural only.',
    tags: ['plural-only'],
    examples: [{ lt: 'Grįžtame į kareivines.', en: 'We are returning to barracks.' }],
  },
  {
    lt: 'poligonas',
    en: 'training area; range',
    pron: 'poh-lee-GOH-nahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL1',
    category: 'places',
    emoji: '🎯',
    examples: [{ lt: 'Rytoj vykstame į poligoną.', en: 'Tomorrow we go to the training area.' }],
  },
  {
    lt: 'sargyba',
    en: 'guard duty; the guard',
    pron: 'sahr-GEE-bah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL1',
    category: 'places',
    emoji: '🛡️',
    examples: [{ lt: 'Šiąnakt stoviu sargyboje.', en: 'Tonight I am on guard duty.' }],
  },
  {
    lt: 'postas',
    en: 'post; sentry position',
    pron: 'POHS-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL1',
    category: 'places',
    emoji: '📍',
    examples: [{ lt: 'Grįžk į postą.', en: 'Return to your post.' }],
  },

  // ── First commands ────────────────────────────────────────────────────────
  {
    lt: 'Ramiai!',
    en: 'Attention! (stand to attention)',
    pron: 'rah-MYIGH',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '🧍',
    grammar: 'An adverb used as a drill command — literally “calmly, still”.',
    usage:
      'The Lithuanian drill command for the position of attention. Do not use “Dėmesio!” for this — that word warns or draws attention, it does not put a formation at attention.',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Būrys, ramiai!', en: 'Platoon, attention!' }],
  },
  {
    lt: 'Laisvai!',
    en: 'At ease! ; Stand easy!',
    pron: 'lighs-VIGH',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '🧎',
    grammar: 'Adverb “laisvai” = freely. The counterpart of “Ramiai!”.',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Skyrius, laisvai!', en: 'Section, at ease!' }],
  },
  {
    lt: 'Stok!',
    en: 'Halt! ; Stop!',
    pron: 'stohk',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '✋',
    grammar:
      'Singular imperative of “stoti”. To a group: “Stokite!”. The infinitive “stoti” is never shouted as a command.',
    usage: 'Also the sentry’s challenge: “Stok! Kas eina?” — Halt! Who goes there?',
    tags: ['command'],
    examples: [{ lt: 'Stok! Kas eina?', en: 'Halt! Who goes there?' }],
  },
  {
    lt: 'Pirmyn!',
    en: 'Forward! ; Move!',
    pron: 'peer-MEEN',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '➡️',
    grammar: 'An adverb of direction used as a command.',
    usage: 'Also the Lithuanian equivalent of “Let’s go!” at the start of a bound.',
    tags: ['command'],
    examples: [{ lt: 'Skyrius, pirmyn!', en: 'Section, move!' }],
  },
  {
    lt: 'Gulk!',
    en: 'Get down! ; Down!',
    pron: 'goolk',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '⬇️',
    grammar:
      'Singular imperative of “gulti” (to lie down). To a group: “Gulkite!”. Not “gulėti”, which is the infinitive “to be lying”.',
    tags: ['command'],
    examples: [{ lt: 'Gulk! Priedanga!', en: 'Get down! Take cover!' }],
  },
  {
    lt: 'Kelkis!',
    en: 'Get up! ; On your feet!',
    pron: 'KEL-kis',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '⬆️',
    grammar: 'Reflexive imperative of “keltis”. To a group: “Kelkitės!”.',
    tags: ['command'],
    examples: [{ lt: 'Kelkitės, judam!', en: 'On your feet, moving!' }],
  },
  {
    lt: 'Dėmesio!',
    en: 'Attention! (warning — listen up / look out)',
    pron: 'day-MEH-syoh',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '⚠️',
    grammar: 'Genitive of “dėmesys” (attention) used as an interjection.',
    usage:
      'Opens an announcement or a radio message and marks a hazard on signs. It is not the drill command for the position of attention — that is “Ramiai!”.',
    tags: ['command', 'radio'],
    examples: [{ lt: 'Dėmesio! Klausykite įsakymo.', en: 'Attention! Listen to the order.' }],
  },
  {
    lt: 'Greičiau!',
    en: 'Faster! ; Move it!',
    pron: 'gray-CHOW',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '💨',
    grammar: 'Comparative of “greitai” (quickly).',
    tags: ['command'],
    examples: [{ lt: 'Greičiau, kariai!', en: 'Faster, soldiers!' }],
  },
  {
    lt: 'Tyliai!',
    en: 'Quiet! ; Silence!',
    pron: 'TEE-lyigh',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '🤫',
    grammar: 'Adverb “tyliai” = quietly.',
    tags: ['command'],
    examples: [{ lt: 'Tyliai! Klausom.', en: 'Quiet! We’re listening.' }],
  },
  {
    lt: 'Sek mane!',
    en: 'Follow me!',
    pron: 'sek MAH-neh',
    pos: 'command',
    level: 'MIL1',
    category: 'commands',
    emoji: '👣',
    grammar: 'Imperative of “sekti” + accusative “mane”. To a group: “Sekite mane!”.',
    tags: ['command'],
    alt: ['sekite mane'],
    examples: [{ lt: 'Sekite mane, po vieną!', en: 'Follow me, one at a time!' }],
  },

  // ── Digits for grids and radio ────────────────────────────────────────────
  {
    lt: 'nulis',
    en: 'zero',
    pron: 'NOO-lis',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '0️⃣',
    usage: 'Read digit by digit in grid references and frequencies.',
    tags: ['radio'],
    examples: [{ lt: 'Kvadratas trys nulis penki.', en: 'Grid three zero five.' }],
  },
  {
    lt: 'vienas',
    en: 'one',
    pron: 'VYEH-nahs',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '1️⃣',
    grammar: 'Feminine “viena”. Agrees with its noun: “vienas karys”, “viena kuopa”.',
    alt: ['viena'],
    examples: [{ lt: 'Vienas sužeistas.', en: 'One casualty.' }],
  },
  {
    lt: 'du',
    en: 'two',
    pron: 'doo',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '2️⃣',
    grammar: 'Feminine “dvi”: “du kariai”, but “dvi mašinos”.',
    alt: ['dvi'],
    examples: [{ lt: 'Du priešo kariai.', en: 'Two enemy soldiers.' }],
  },
  {
    lt: 'trys',
    en: 'three',
    pron: 'trees',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '3️⃣',
    examples: [{ lt: 'Trys transporto priemonės.', en: 'Three vehicles.' }],
  },
  {
    lt: 'keturi',
    en: 'four',
    pron: 'keh-too-REE',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '4️⃣',
    grammar: 'Feminine “keturios”.',
    alt: ['keturios'],
    examples: [{ lt: 'Keturi kariai poste.', en: 'Four soldiers at the post.' }],
  },
  {
    lt: 'penki',
    en: 'five',
    pron: 'pen-KEE',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '5️⃣',
    grammar:
      'From five upwards the counted noun takes the genitive plural: “penki kariai” but “penkiolika karių”.',
    alt: ['penkios'],
    examples: [{ lt: 'Penki šimtai metrų.', en: 'Five hundred metres.' }],
  },
  {
    lt: 'šeši',
    en: 'six',
    pron: 'sheh-SHEE',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '6️⃣',
    alt: ['šešios'],
    examples: [{ lt: 'Šeši nuliai du.', en: 'Six zero two.' }],
  },
  {
    lt: 'septyni',
    en: 'seven',
    pron: 'sep-tee-NEE',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '7️⃣',
    alt: ['septynios'],
    examples: [{ lt: 'Septyni kariai skyriuje.', en: 'Seven soldiers in the section.' }],
  },
  {
    lt: 'aštuoni',
    en: 'eight',
    pron: 'ash-twoh-NEE',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '8️⃣',
    alt: ['aštuonios'],
    examples: [{ lt: 'Aštuoni šoviniai.', en: 'Eight rounds.' }],
  },
  {
    lt: 'devyni',
    en: 'nine',
    pron: 'deh-vee-NEE',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '9️⃣',
    alt: ['devynios'],
    examples: [{ lt: 'Devyni nuliai vienas.', en: 'Nine zero one.' }],
  },
  {
    lt: 'dešimt',
    en: 'ten',
    pron: 'DEH-shimt',
    pos: 'numeral',
    level: 'MIL1',
    category: 'numbers',
    emoji: '🔟',
    grammar: 'Takes the genitive plural: “dešimt karių” (ten soldiers).',
    examples: [{ lt: 'Dešimt minučių iki išvykimo.', en: 'Ten minutes until departure.' }],
  },
];
