import type { Word } from '../types.js';

/**
 * MIL2 — Kareivis / Soldier.
 *
 * Drill and ceremony, formations, and the vocabulary of movement: cardinal
 * directions, relative positions, and the prepositions that govern them.
 */
export const mil2Words: Word[] = [
  // ── Drill commands ────────────────────────────────────────────────────────
  {
    lt: 'Rikiuotis!',
    en: 'Fall in! ; Form up!',
    pron: 'ree-KYOO-oh-tis',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '👥',
    grammar: 'Reflexive imperative of “rikiuotis” (to form up). Group form: “Rikiuokitės!”.',
    tags: ['drill', 'command'],
    alt: ['rikiuokitės'],
    examples: [{ lt: 'Būrys, rikiuotis!', en: 'Platoon, fall in!' }],
  },
  {
    lt: 'Lygiuok!',
    en: 'Dress! ; Align!',
    pron: 'lee-GYOOK',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '📏',
    grammar: 'Imperative of “lygiuoti” (to align, to dress a rank).',
    usage: 'Given after “Rikiuotis!” so the rank straightens itself on the right-hand marker.',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Į dešinę — lygiuok!', en: 'Right — dress!' }],
  },
  {
    lt: 'Dešinėn!',
    en: 'Right face! ; Right turn!',
    pron: 'deh-shee-NAYN',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '↩️',
    grammar:
      'The illative case of “dešinė” (right side) — literally “into the right”. Same pattern as “Kairėn!”.',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Skyrius, dešinėn!', en: 'Section, right face!' }],
  },
  {
    lt: 'Kairėn!',
    en: 'Left face! ; Left turn!',
    pron: 'kigh-RAYN',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '↪️',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Būrys, kairėn!', en: 'Platoon, left face!' }],
  },
  {
    lt: 'Aplink!',
    en: 'About face! ; Turn around!',
    pron: 'ah-PLINK',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '🔄',
    grammar:
      'As a preposition “aplink” means “around” and takes the accusative: “aplink pastatą” (around the building).',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Kariai, aplink!', en: 'Soldiers, about face!' }],
  },
  {
    lt: 'Žengte marš!',
    en: 'Forward, march!',
    pron: 'ZHENG-teh mahrsh',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '🚶',
    grammar: '“Žengte” is a manner form of “žengti” (to step). “Marš” is the executive word.',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Būrys, žengte marš!', en: 'Platoon, forward march!' }],
  },
  {
    lt: 'Bėgte marš!',
    en: 'Double time, march!',
    pron: 'BAYG-teh mahrsh',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '🏃',
    grammar: 'From “bėgti” (to run).',
    tags: ['drill', 'command'],
    examples: [{ lt: 'Skyrius, bėgte marš!', en: 'Section, double time march!' }],
  },
  {
    lt: 'Išsiskirstyti!',
    en: 'Fall out! ; Dismissed!',
    pron: 'ish-see-SKEERS-tee-tee',
    pos: 'command',
    level: 'MIL2',
    category: 'drill',
    emoji: '💨',
    grammar: 'Also heard as “Skirstytis!”.',
    tags: ['drill', 'command'],
    alt: ['skirstytis'],
    examples: [{ lt: 'Laisvai, išsiskirstyti!', en: 'At ease, fall out!' }],
  },
  {
    lt: 'rikiuotė',
    en: 'formation; drill',
    pron: 'ree-KYOO-oh-tay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL2',
    category: 'drill',
    emoji: '🧱',
    examples: [{ lt: 'Rytinė rikiuotė septintą valandą.', en: 'Morning formation at 07:00.' }],
  },
  {
    lt: 'eilė',
    en: 'rank; line (of soldiers)',
    pron: 'AY-lay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL2',
    category: 'drill',
    emoji: '➖',
    grammar: '“Į dvi eiles” = in two ranks.',
    examples: [{ lt: 'Stokite į dvi eiles.', en: 'Form up in two ranks.' }],
  },
  {
    lt: 'vora',
    en: 'column; file',
    pron: 'voh-RAH',
    pos: 'noun',
    gender: 'f',
    level: 'MIL2',
    category: 'drill',
    emoji: '⬇️',
    grammar: '“Po vieną vora” = single file.',
    examples: [{ lt: 'Judame vora po vieną.', en: 'We move in single file.' }],
  },
  {
    lt: 'atstumas',
    en: 'distance; interval',
    pron: 'AHT-stoo-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL2',
    category: 'drill',
    emoji: '📐',
    usage: 'Also the tactical spacing between soldiers: “Laikykite atstumą!” — Keep your spacing!',
    examples: [{ lt: 'Atstumas penki metrai.', en: 'Interval five metres.' }],
  },

  // ── Movement verbs ────────────────────────────────────────────────────────
  {
    lt: 'judėti',
    en: 'to move',
    pron: 'yoo-DAY-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '🏃',
    grammar: 'judu, judi, juda, judame, judate, juda.',
    usage: '“Judu!” = Moving! — shouted when you break cover. “Judam!” = Let’s move!',
    tags: ['contact'],
    examples: [{ lt: 'Judu! Dengk!', en: 'Moving! Cover me!' }],
  },
  {
    lt: 'bėgti',
    en: 'to run',
    pron: 'BAYG-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '🏃‍♂️',
    grammar: 'bėgu, bėgi, bėga, bėgame, bėgate, bėga.',
    examples: [{ lt: 'Bėk prie priedangos!', en: 'Run to cover!' }],
  },
  {
    lt: 'šliaužti',
    en: 'to crawl',
    pron: 'SHLYOWZH-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '🐊',
    grammar: 'šliaužiu, šliauži, šliaužia. Imperative: “Šliaužk!”.',
    examples: [{ lt: 'Šliaužk iki griovio.', en: 'Crawl to the ditch.' }],
  },
  {
    lt: 'slėptis',
    en: 'to take cover; to hide',
    pron: 'SLAYP-tis',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '🫣',
    grammar: 'Reflexive: slepiuosi, slepiesi, slepiasi. Imperative “Slėpkis!” / “Slėpkitės!”.',
    tags: ['contact'],
    examples: [{ lt: 'Slėpkitės! Minosvaidžiai!', en: 'Take cover! Mortars!' }],
  },
  {
    lt: 'dengti',
    en: 'to cover (provide covering fire)',
    pron: 'DENG-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '🛡️',
    grammar: 'dengiu, dengi, dengia. Imperative “Dengk!”.',
    usage: 'The buddy-pair call and response: “Judu!” — “Dengiu!”',
    tags: ['contact'],
    examples: [{ lt: 'Dengiu! Judėk!', en: 'Covering! Move!' }],
  },
  {
    lt: 'trauktis',
    en: 'to withdraw; to pull back',
    pron: 'TROWK-tis',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '↩️',
    grammar: 'Reflexive: traukiuosi, traukiesi, traukiasi. Imperative “Trauktis!”.',
    examples: [{ lt: 'Skyrius, trauktis!', en: 'Section, withdraw!' }],
  },
  {
    lt: 'pulti',
    en: 'to attack; to assault',
    pron: 'POOL-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '⚔️',
    grammar: 'puolu, puoli, puola. Its object takes the accusative.',
    examples: [{ lt: 'Puolame iš dešinės.', en: 'We attack from the right.' }],
  },
  {
    lt: 'laukti',
    en: 'to wait',
    pron: 'LOWK-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '⏳',
    grammar: 'laukiu, lauki, laukia. Takes the genitive: “laukiu įsakymo”.',
    usage: '“Laukite!” = Wait / Standby — also the standard radio hold.',
    tags: ['radio'],
    examples: [{ lt: 'Laukite mano signalo.', en: 'Wait for my signal.' }],
  },
  {
    lt: 'sustoti',
    en: 'to stop; to halt',
    pron: 'soos-TOH-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '🛑',
    grammar: 'sustoju, sustoji, sustoja.',
    examples: [{ lt: 'Sustojame prie miško.', en: 'We halt at the treeline.' }],
  },
  {
    lt: 'grįžti',
    en: 'to return; to come back',
    pron: 'GREEZH-tee',
    pos: 'verb',
    level: 'MIL2',
    category: 'movement',
    emoji: '🔙',
    grammar: 'grįžtu, grįžti, grįžta. Past: grįžau, grįžai, grįžo.',
    examples: [{ lt: 'Grįžtame į bazę.', en: 'We are returning to base.' }],
  },
  {
    lt: 'žingsnis',
    en: 'step; pace',
    pron: 'ZHINGS-nis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL2',
    category: 'movement',
    emoji: '👣',
    usage: 'Used for rough pacing distance: “šimtas žingsnių” — a hundred paces.',
    examples: [{ lt: 'Dvidešimt žingsnių į priekį.', en: 'Twenty paces forward.' }],
  },

  // ── Relative direction ────────────────────────────────────────────────────
  {
    lt: 'kairė',
    en: 'left (side)',
    pron: 'KIGH-ray',
    pos: 'noun',
    gender: 'f',
    level: 'MIL2',
    category: 'directions',
    emoji: '⬅️',
    grammar:
      'Three forms to know: “kairė” (the left side), “į kairę” (to the left), “kairėje” (on the left).',
    examples: [{ lt: 'Priešas kairėje!', en: 'Enemy on the left!' }],
  },
  {
    lt: 'dešinė',
    en: 'right (side)',
    pron: 'DEH-shee-nay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL2',
    category: 'directions',
    emoji: '➡️',
    grammar: '“Į dešinę” (to the right), “dešinėje” (on the right).',
    examples: [{ lt: 'Judame į dešinę.', en: 'We are moving to the right.' }],
  },
  {
    lt: 'tiesiai',
    en: 'straight ahead',
    pron: 'TYEH-shigh',
    pos: 'adverb',
    level: 'MIL2',
    category: 'directions',
    emoji: '⬆️',
    examples: [{ lt: 'Tiesiai iki kelio.', en: 'Straight ahead to the road.' }],
  },
  {
    lt: 'atgal',
    en: 'back; to the rear',
    pron: 'aht-GAHL',
    pos: 'adverb',
    level: 'MIL2',
    category: 'directions',
    emoji: '🔙',
    examples: [{ lt: 'Penkiasdešimt metrų atgal.', en: 'Fifty metres to the rear.' }],
  },
  {
    lt: 'priekyje',
    en: 'in front; ahead',
    pron: 'PRYEH-kee-yeh',
    pos: 'adverb',
    level: 'MIL2',
    category: 'directions',
    emoji: '🔜',
    grammar: 'Locative of “priekis” (the front). “Į priekį” = forwards.',
    examples: [{ lt: 'Priekyje pastatas.', en: 'A building ahead.' }],
  },
  {
    lt: 'už',
    en: 'behind; beyond',
    pron: 'oozh',
    pos: 'preposition',
    level: 'MIL2',
    category: 'directions',
    emoji: '🔚',
    grammar: 'Takes the genitive: “už pastato” (behind the building), “už manęs” (behind me).',
    examples: [{ lt: 'Priešas už tilto.', en: 'The enemy is beyond the bridge.' }],
  },
  {
    lt: 'aplink',
    en: 'around',
    pron: 'ah-PLINK',
    pos: 'preposition',
    level: 'MIL2',
    category: 'directions',
    emoji: '🔄',
    grammar: 'Takes the accusative: “aplink pastatą” (around the building).',
    examples: [{ lt: 'Einame aplink mišką.', en: 'We are going around the wood.' }],
  },
  {
    lt: 'šone',
    en: 'on the flank; to the side',
    pron: 'SHOH-neh',
    pos: 'adverb',
    level: 'MIL2',
    category: 'directions',
    emoji: '↔️',
    grammar: 'Locative of “šonas” (side). The military term for a flank is also “flangas”.',
    alt: ['flangas'],
    examples: [{ lt: 'Judėjimas dešiniame šone.', en: 'Movement on the right flank.' }],
  },
  {
    lt: 'tarp',
    en: 'between; among',
    pron: 'tahrp',
    pos: 'preposition',
    level: 'MIL2',
    category: 'directions',
    emoji: '↔️',
    grammar: 'Takes the genitive: “tarp medžių” (among the trees).',
    examples: [{ lt: 'Priešas tarp namų.', en: 'The enemy is among the houses.' }],
  },
  {
    lt: 'prie',
    en: 'at; near; by',
    pron: 'pryeh',
    pos: 'preposition',
    level: 'MIL2',
    category: 'directions',
    emoji: '📍',
    grammar: 'Takes the genitive: “prie kelio” (by the road).',
    examples: [{ lt: 'Susitinkame prie tilto.', en: 'We meet at the bridge.' }],
  },
  {
    lt: 'po',
    en: 'under; after',
    pron: 'poh',
    pos: 'preposition',
    level: 'MIL2',
    category: 'directions',
    emoji: '⬇️',
    grammar:
      'Location takes the instrumental: “po tiltu” (under the bridge). Time takes the genitive: “po pietų” (after noon).',
    examples: [{ lt: 'Priedanga po tiltu.', en: 'Cover under the bridge.' }],
  },
  {
    lt: 'per',
    en: 'across; through',
    pron: 'pehr',
    pos: 'preposition',
    level: 'MIL2',
    category: 'directions',
    emoji: '↗️',
    grammar: 'Takes the accusative: “per upę” (across the river).',
    examples: [{ lt: 'Judame per lauką.', en: 'We move across the field.' }],
  },

  // ── Cardinal directions ───────────────────────────────────────────────────
  {
    lt: 'šiaurė',
    en: 'north',
    pron: 'SHYOW-ray',
    pos: 'noun',
    gender: 'f',
    level: 'MIL2',
    category: 'cardinal',
    emoji: '🧭',
    grammar: '“Į šiaurę” = to the north; “šiaurėje” = in the north.',
    examples: [{ lt: 'Priešas į šiaurę nuo kelio.', en: 'Enemy north of the road.' }],
  },
  {
    lt: 'pietūs',
    en: 'south',
    pron: 'PYEH-toos',
    pos: 'noun',
    gender: 'm',
    level: 'MIL2',
    category: 'cardinal',
    emoji: '🧭',
    grammar: 'Plural only. The same word also means “lunch” — context makes it unambiguous.',
    tags: ['plural-only'],
    examples: [{ lt: 'Judame į pietus.', en: 'We are moving south.' }],
  },
  {
    lt: 'rytai',
    en: 'east',
    pron: 'REE-tigh',
    pos: 'noun',
    gender: 'm',
    level: 'MIL2',
    category: 'cardinal',
    emoji: '🧭',
    grammar: 'Plural only. Related to “rytas” (morning) — where the sun rises.',
    tags: ['plural-only'],
    examples: [{ lt: 'Sektorius rytuose.', en: 'Sector to the east.' }],
  },
  {
    lt: 'vakarai',
    en: 'west',
    pron: 'vah-kah-RIGH',
    pos: 'noun',
    gender: 'm',
    level: 'MIL2',
    category: 'cardinal',
    emoji: '🧭',
    grammar: 'Plural only. Related to “vakaras” (evening).',
    tags: ['plural-only'],
    examples: [{ lt: 'Vėjas iš vakarų.', en: 'Wind from the west.' }],
  },
  {
    lt: 'šiaurės rytai',
    en: 'north-east',
    pron: 'SHYOW-rays REE-tigh',
    pos: 'phrase',
    level: 'MIL2',
    category: 'cardinal',
    emoji: '↗️',
    grammar: 'Genitive + noun. North-west is “šiaurės vakarai”.',
    examples: [{ lt: 'Judėjimas iš šiaurės rytų.', en: 'Movement from the north-east.' }],
  },
  {
    lt: 'pietryčiai',
    en: 'south-east',
    pron: 'pyeht-REE-chigh',
    pos: 'noun',
    gender: 'm',
    level: 'MIL2',
    category: 'cardinal',
    emoji: '↘️',
    grammar: 'A single compound word, unlike “šiaurės rytai”. South-west is “pietvakariai”.',
    tags: ['plural-only'],
    examples: [{ lt: 'Priešas pietryčiuose.', en: 'Enemy to the south-east.' }],
  },
  {
    lt: 'kryptis',
    en: 'direction; bearing',
    pron: 'kreep-TIS',
    pos: 'noun',
    gender: 'f',
    level: 'MIL2',
    category: 'cardinal',
    emoji: '➡️',
    examples: [{ lt: 'Judėjimo kryptis — šiaurė.', en: 'Direction of movement — north.' }],
  },
];
