import type { Word } from '../types.js';

/**
 * MIL3 — Skyrininkas / Section Member.
 *
 * Terrain description, map reading and land navigation: the words you need to
 * say where you are, where you are going, and what the ground looks like.
 */
export const mil3Words: Word[] = [
  // ── Map & navigation ──────────────────────────────────────────────────────
  {
    lt: 'žemėlapis',
    en: 'map',
    pron: 'zheh-MAY-lah-pis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🗺️',
    grammar: 'From “žemė” (earth, land) + “lapas” (sheet).',
    examples: [{ lt: 'Pažymėk poziciją žemėlapyje.', en: 'Mark the position on the map.' }],
  },
  {
    lt: 'kompasas',
    en: 'compass',
    pron: 'kohm-PAH-sahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🧭',
    examples: [{ lt: 'Patikrink kryptį kompasu.', en: 'Check the direction with the compass.' }],
  },
  {
    lt: 'azimutas',
    en: 'bearing; azimuth',
    pron: 'ah-zee-MOO-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '📐',
    usage: 'Read digit by digit: “azimutas du keturi nulis” — bearing two four zero.',
    examples: [{ lt: 'Azimutas trys šeši nulis.', en: 'Bearing three six zero.' }],
  },
  {
    lt: 'koordinatės',
    en: 'coordinates',
    pron: 'koh-ohr-dee-NAH-tays',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'navigation',
    emoji: '📍',
    grammar: 'Plural only.',
    tags: ['plural-only', 'radio'],
    examples: [{ lt: 'Perduodu koordinates.', en: 'I am passing the coordinates.' }],
  },
  {
    lt: 'kvadratas',
    en: 'grid square',
    pron: 'kvah-DRAH-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🔲',
    usage: 'Standard way to report a rough location: “kvadratas keturi du, penki vienas”.',
    tags: ['radio'],
    examples: [{ lt: 'Priešas kvadrate keturi du.', en: 'Enemy in grid square four two.' }],
  },
  {
    lt: 'mastelis',
    en: 'scale (of a map)',
    pron: 'MAHS-teh-lis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '📏',
    examples: [
      {
        lt: 'Žemėlapio mastelis vienas prie penkiasdešimt tūkstančių.',
        en: 'The map scale is one to fifty thousand.',
      },
    ],
  },
  {
    lt: 'horizontalės',
    en: 'contour lines',
    pron: 'hoh-ree-zohn-TAH-lays',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'navigation',
    emoji: '〰️',
    grammar: 'Usually plural in map-reading contexts.',
    examples: [
      { lt: 'Tankios horizontalės — status šlaitas.', en: 'Close contours — a steep slope.' },
    ],
  },
  {
    lt: 'aukštis',
    en: 'height; elevation',
    pron: 'OWKSH-tis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '⛰️',
    examples: [
      { lt: 'Aukštis šimtas keturiasdešimt metrų.', en: 'Elevation one hundred and forty metres.' },
    ],
  },
  {
    lt: 'orientyras',
    en: 'landmark; reference point',
    pron: 'oh-ree-en-TEE-rahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🗼',
    usage: 'Used to hand off a target: “Orientyras vienas — bokštas. Nuo jo į kairę.”',
    examples: [{ lt: 'Orientyras — vienišas medis.', en: 'Reference point — the lone tree.' }],
  },
  {
    lt: 'maršrutas',
    en: 'route',
    pron: 'mahrsh-ROO-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🛤️',
    examples: [{ lt: 'Maršrutas eina per mišką.', en: 'The route goes through the forest.' }],
  },
  {
    lt: 'susitikimo taškas',
    en: 'rally point; RV',
    pron: 'soo-see-tee-KEE-moh TAHSH-kahs',
    pos: 'phrase',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🎯',
    grammar: 'Genitive “susitikimo” (of meeting) + “taškas” (point).',
    examples: [{ lt: 'Susitikimo taškas prie tilto.', en: 'Rally point at the bridge.' }],
  },
  {
    lt: 'orientuotis',
    en: 'to orient oneself; to get one’s bearings',
    pron: 'oh-ree-en-TWOH-tis',
    pos: 'verb',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🧭',
    grammar: 'Reflexive: orientuojuosi, orientuojiesi, orientuojasi.',
    tags: ['reflexive'],
    examples: [{ lt: 'Orientuojuosi pagal kompasą.', en: 'I am orienting myself by compass.' }],
  },
  {
    lt: 'pažymėti',
    en: 'to mark; to plot',
    pron: 'pah-zhee-MAY-tee',
    pos: 'verb',
    level: 'MIL3',
    category: 'navigation',
    emoji: '✏️',
    grammar: 'pažymiu, pažymi, pažymi. Imperative “Pažymėk!” / “Pažymėkite!”.',
    examples: [{ lt: 'Pažymėkite taikinį žemėlapyje.', en: 'Plot the target on the map.' }],
  },
  {
    lt: 'nustatyti',
    en: 'to determine; to establish',
    pron: 'noos-tah-TEE-tee',
    pos: 'verb',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🔎',
    grammar: 'nustatau, nustatai, nustato.',
    examples: [{ lt: 'Nustatykite savo koordinates.', en: 'Determine your coordinates.' }],
  },
  {
    lt: 'metras',
    en: 'metre',
    pron: 'MEH-trahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '📏',
    grammar: 'Genitive plural “metrų”, used after numbers from five up: “šimtas metrų”.',
    examples: [{ lt: 'Taikinys už trijų šimtų metrų.', en: 'Target at three hundred metres.' }],
  },
  {
    lt: 'kilometras',
    en: 'kilometre',
    pron: 'kee-loh-MEH-trahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'navigation',
    emoji: '🛣️',
    examples: [{ lt: 'Iki bazės du kilometrai.', en: 'Two kilometres to base.' }],
  },

  // ── Terrain ───────────────────────────────────────────────────────────────
  {
    lt: 'miškas',
    en: 'forest; woods',
    pron: 'MISH-kahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🌲',
    usage:
      'Roughly a third of Lithuania is forested — the defining terrain feature of the country.',
    examples: [{ lt: 'Priešas miške.', en: 'Enemy in the woods.' }],
  },
  {
    lt: 'laukas',
    en: 'field; open ground',
    pron: 'LOW-kahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🌾',
    grammar: '“Lauke” also simply means “outside”.',
    examples: [{ lt: 'Atviras laukas — nėra priedangos.', en: 'Open field — no cover.' }],
  },
  {
    lt: 'pelkė',
    en: 'marsh; swamp; bog',
    pron: 'PEL-kay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🪵',
    usage: 'Common in Lithuania and a serious mobility obstacle — always report it.',
    examples: [{ lt: 'Kelias uždarytas — pelkė.', en: 'Route closed — marsh.' }],
  },
  {
    lt: 'upė',
    en: 'river',
    pron: 'OO-pay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🏞️',
    examples: [{ lt: 'Upė per gili brasti.', en: 'The river is too deep to ford.' }],
  },
  {
    lt: 'ežeras',
    en: 'lake',
    pron: 'EH-zheh-rahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🏞️',
    examples: [{ lt: 'Stovykla prie ežero.', en: 'Camp by the lake.' }],
  },
  {
    lt: 'kalva',
    en: 'hill',
    pron: 'kahl-VAH',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'terrain',
    emoji: '⛰️',
    examples: [{ lt: 'Pozicija ant kalvos.', en: 'Position on the hill.' }],
  },
  {
    lt: 'slėnis',
    en: 'valley',
    pron: 'SLAY-nis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🏔️',
    examples: [{ lt: 'Judame slėniu.', en: 'We are moving along the valley.' }],
  },
  {
    lt: 'griovys',
    en: 'ditch',
    pron: 'gryoh-VEES',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🕳️',
    usage: 'The nearest ready-made cover along most Lithuanian roads.',
    examples: [{ lt: 'Priedanga griovyje!', en: 'Cover in the ditch!' }],
  },
  {
    lt: 'kelias',
    en: 'road',
    pron: 'KEH-lyahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🛣️',
    grammar: 'Also means “way, journey”. Plural “keliai”.',
    examples: [{ lt: 'Kelias užminuotas.', en: 'The road is mined.' }],
  },
  {
    lt: 'takas',
    en: 'path; track',
    pron: 'TAH-kahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🥾',
    examples: [{ lt: 'Siauras takas per mišką.', en: 'A narrow path through the forest.' }],
  },
  {
    lt: 'tiltas',
    en: 'bridge',
    pron: 'TIL-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🌉',
    examples: [{ lt: 'Tiltas sunaikintas.', en: 'The bridge is destroyed.' }],
  },
  {
    lt: 'geležinkelis',
    en: 'railway',
    pron: 'geh-leh-ZHIN-keh-lis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🛤️',
    grammar: 'Literally “iron road”.',
    examples: [{ lt: 'Geležinkelis kerta kelią.', en: 'The railway crosses the road.' }],
  },
  {
    lt: 'pastatas',
    en: 'building; structure',
    pron: 'PAHS-tah-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🏢',
    examples: [{ lt: 'Dviaukštis pastatas kairėje.', en: 'A two-storey building on the left.' }],
  },
  {
    lt: 'kaimas',
    en: 'village',
    pron: 'KIGH-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🏘️',
    examples: [{ lt: 'Kaimas už dviejų kilometrų.', en: 'A village two kilometres away.' }],
  },
  {
    lt: 'priedanga',
    en: 'cover; concealment',
    pron: 'pryeh-DAHN-gah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🛡️',
    usage: '“Į priedangą!” = Take cover! — one of the most urgent commands in the language.',
    tags: ['contact'],
    examples: [{ lt: 'Į priedangą!', en: 'Take cover!' }],
  },
  {
    lt: 'kliūtis',
    en: 'obstacle',
    pron: 'klyoo-TIS',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'terrain',
    emoji: '🚧',
    examples: [{ lt: 'Kliūtis kelyje — medžiai.', en: 'Obstacle on the route — trees.' }],
  },
  {
    lt: 'praeinamas',
    en: 'passable; trafficable',
    pron: 'prah-AY-nah-mahs',
    pos: 'adjective',
    level: 'MIL3',
    category: 'terrain',
    emoji: '✅',
    grammar: 'Feminine “praeinama”. Negative: “nepraeinamas” (impassable).',
    alt: ['praeinama'],
    examples: [{ lt: 'Kelias praeinamas transportui.', en: 'The route is passable for vehicles.' }],
  },

  // ── Time ──────────────────────────────────────────────────────────────────
  {
    lt: 'laikas',
    en: 'time',
    pron: 'LIGH-kahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL3',
    category: 'time',
    emoji: '🕒',
    examples: [{ lt: 'Kiek laiko iki išvykimo?', en: 'How long until departure?' }],
  },
  {
    lt: 'valanda',
    en: 'hour; o’clock',
    pron: 'vah-lahn-DAH',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'time',
    emoji: '🕐',
    usage:
      'Military times are read digit by digit: 08:00 → “nulis aštuoni nulis nulis”. In ordinary speech: “aštuntą valandą”.',
    examples: [{ lt: 'Išvykstame aštuntą valandą.', en: 'We depart at eight o’clock.' }],
  },
  {
    lt: 'minutė',
    en: 'minute',
    pron: 'mee-NOO-tay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'time',
    emoji: '⏱️',
    examples: [{ lt: 'Penkios minutės iki starto.', en: 'Five minutes to start.' }],
  },
  {
    lt: 'para',
    en: 'a 24-hour period; a full day',
    pron: 'PAH-rah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'time',
    emoji: '🌗',
    grammar: 'No single English word — “diena” is the daylight day, “para” is day + night.',
    examples: [{ lt: 'Užduotis truks parą.', en: 'The task will last twenty-four hours.' }],
  },
  {
    lt: 'naktis',
    en: 'night',
    pron: 'nahk-TIS',
    pos: 'noun',
    gender: 'f',
    level: 'MIL3',
    category: 'time',
    emoji: '🌙',
    examples: [{ lt: 'Judėsime naktį.', en: 'We will move at night.' }],
  },
  {
    lt: 'prieš',
    en: 'before; in front of; against',
    pron: 'pryehsh',
    pos: 'preposition',
    level: 'MIL3',
    category: 'time',
    emoji: '⏪',
    grammar: 'Takes the accusative: “prieš aušrą” (before dawn).',
    examples: [{ lt: 'Pozicijas užimame prieš aušrą.', en: 'We occupy positions before dawn.' }],
  },
  {
    lt: 'iki',
    en: 'until; up to',
    pron: 'EE-kee',
    pos: 'preposition',
    level: 'MIL3',
    category: 'time',
    emoji: '⏭️',
    grammar: 'Takes the genitive: “iki vidurnakčio” (until midnight).',
    examples: [
      { lt: 'Laikome poziciją iki vidurnakčio.', en: 'We hold the position until midnight.' },
    ],
  },
];
