import type { Word } from '../types.js';

/**
 * MIL4 — Specialistas / Specialist.
 *
 * Weapons, personal and section equipment, vehicles and supply, plus the rank
 * ladder and unit structure of the Lithuanian Armed Forces.
 *
 * Rank names follow the Lithuanian Armed Forces system, in which the NCO ladder
 * is built on “puskarininkis” rather than the Western “sergeant”. The list here
 * is a simplified teaching ladder — see docs/LINGUISTIC_NOTES.md.
 */
export const mil4Words: Word[] = [
  // ── Weapons ───────────────────────────────────────────────────────────────
  {
    lt: 'ginklas',
    en: 'weapon',
    pron: 'GEENK-lahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🔫',
    grammar: 'Plural “ginklai”. “Ginkluotė” = armament, the weapons of a unit collectively.',
    examples: [{ lt: 'Patikrinkite ginklus.', en: 'Check weapons.' }],
  },
  {
    lt: 'šautuvas',
    en: 'rifle',
    pron: 'SHOW-too-vahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🔫',
    grammar: 'From “šauti” (to shoot). “Automatinis šautuvas” = assault rifle.',
    examples: [{ lt: 'Šautuvas užtaisytas.', en: 'The rifle is loaded.' }],
  },
  {
    lt: 'kulkosvaidis',
    en: 'machine gun',
    pron: 'kool-koh-SVIGH-dis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '💥',
    grammar: 'From “kulka” (bullet) + “svaidyti” (to hurl).',
    examples: [{ lt: 'Kulkosvaidis dengia kelią.', en: 'The machine gun covers the road.' }],
  },
  {
    lt: 'minosvaidis',
    en: 'mortar',
    pron: 'mee-noh-SVIGH-dis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🎆',
    examples: [{ lt: 'Minosvaidžių ugnis!', en: 'Mortar fire!' }],
  },
  {
    lt: 'granata',
    en: 'grenade',
    pron: 'grah-NAH-tah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'weapons',
    emoji: '💣',
    usage: '“Granata!” shouted alone is a warning — take cover immediately.',
    tags: ['contact'],
    examples: [{ lt: 'Granata! Gulk!', en: 'Grenade! Get down!' }],
  },
  {
    lt: 'šoviniai',
    en: 'rounds; cartridges',
    pron: 'shoh-VEE-nyigh',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🧨',
    grammar: 'Singular “šovinys”. The collective term for ammunition is “šaudmenys”.',
    alt: ['šaudmenys'],
    examples: [{ lt: 'Baigiasi šoviniai!', en: 'Running out of ammo!' }],
  },
  {
    lt: 'apkaba',
    en: 'magazine (for a weapon)',
    pron: 'ahp-kah-BAH',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🗃️',
    examples: [{ lt: 'Keičiu apkabą!', en: 'Changing magazine!' }],
  },
  {
    lt: 'saugiklis',
    en: 'safety catch',
    pron: 'sow-GEEK-lis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🔒',
    examples: [{ lt: 'Užstatykite saugiklį.', en: 'Put the safety on.' }],
  },
  {
    lt: 'taikinys',
    en: 'target',
    pron: 'tigh-kee-NEES',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🎯',
    examples: [
      { lt: 'Taikinys — dešinėje, du šimtai metrų.', en: 'Target — right, two hundred metres.' },
    ],
  },
  {
    lt: 'šauti',
    en: 'to shoot; to fire',
    pron: 'SHOW-tee',
    pos: 'verb',
    level: 'MIL4',
    category: 'weapons',
    emoji: '💢',
    grammar: 'šaunu, šauni, šauna. Repeated action: “šaudyti”.',
    examples: [{ lt: 'Nešaudyti be įsakymo!', en: 'Do not fire without an order!' }],
  },
  {
    lt: 'Ugnis!',
    en: 'Fire! (open fire)',
    pron: 'oog-NIS',
    pos: 'command',
    level: 'MIL4',
    category: 'weapons',
    emoji: '🔥',
    grammar: 'The noun “ugnis” (fire) used as the executive command.',
    usage: 'Beware the double meaning — “Gaisras!” is the word for an uncontrolled blaze.',
    tags: ['command'],
    examples: [{ lt: 'Skyrius — ugnis!', en: 'Section — fire!' }],
  },
  {
    lt: 'Nutraukti ugnį!',
    en: 'Cease fire!',
    pron: 'noo-TROWK-tee oog-NEE',
    pos: 'command',
    level: 'MIL4',
    category: 'weapons',
    emoji: '✋',
    grammar: '“Ugnį” is the accusative of “ugnis”.',
    tags: ['command'],
    examples: [
      { lt: 'Nutraukti ugnį! Saviškiai priekyje!', en: 'Cease fire! Friendlies to the front!' },
    ],
  },
  {
    lt: 'Užtaisyk!',
    en: 'Load!',
    pron: 'oozh-TIGH-seek',
    pos: 'command',
    level: 'MIL4',
    category: 'weapons',
    emoji: '⬆️',
    grammar: 'Imperative of “užtaisyti” (to load). Group form: “Užtaisykite!”.',
    tags: ['command'],
    alt: ['užtaisykite'],
    examples: [{ lt: 'Ginklus užtaisyti!', en: 'Load weapons!' }],
  },
  {
    lt: 'mina',
    en: 'mine (explosive)',
    pron: 'MEE-nah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'weapons',
    emoji: '⚠️',
    grammar: '“Užminuotas” = mined. “Išminuoti” = to clear mines.',
    examples: [{ lt: 'Dėmesio — minos!', en: 'Warning — mines!' }],
  },
  {
    lt: 'sprogmuo',
    en: 'explosive device',
    pron: 'sprohg-MWOH',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'weapons',
    emoji: '💥',
    grammar: 'Irregular: genitive “sprogmens”, plural “sprogmenys”.',
    tags: ['irregular'],
    examples: [{ lt: 'Rastas sprogmuo prie kelio.', en: 'An explosive device found by the road.' }],
  },

  // ── Personal equipment ────────────────────────────────────────────────────
  {
    lt: 'uniforma',
    en: 'uniform',
    pron: 'oo-nee-FOHR-mah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🥋',
    examples: [{ lt: 'Lauko uniforma.', en: 'Field uniform.' }],
  },
  {
    lt: 'šalmas',
    en: 'helmet',
    pron: 'SHAHL-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'equipment',
    emoji: '⛑️',
    examples: [{ lt: 'Užsidėkite šalmus.', en: 'Put on your helmets.' }],
  },
  {
    lt: 'neperšaunama liemenė',
    en: 'body armour; ballistic vest',
    pron: 'neh-per-SHOW-nah-mah lyeh-MEH-nay',
    pos: 'phrase',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🦺',
    grammar: 'Literally “un-shoot-through-able vest”. Often shortened to just “liemenė”.',
    alt: ['liemenė'],
    examples: [
      { lt: 'Be neperšaunamos liemenės neišeiname.', en: 'We don’t go out without body armour.' },
    ],
  },
  {
    lt: 'kuprinė',
    en: 'rucksack; backpack',
    pron: 'koo-pree-NAY',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🎒',
    examples: [{ lt: 'Kuprinė per sunki.', en: 'The rucksack is too heavy.' }],
  },
  {
    lt: 'batai',
    en: 'boots',
    pron: 'BAH-tigh',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🥾',
    grammar: 'Singular “batas”, but boots are normally spoken of in the plural.',
    examples: [{ lt: 'Batai peršlapo.', en: 'The boots got soaked through.' }],
  },
  {
    lt: 'žiūronai',
    en: 'binoculars',
    pron: 'zhoo-roh-NIGH',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🔭',
    grammar: 'Plural only.',
    tags: ['plural-only'],
    examples: [{ lt: 'Stebiu per žiūronus.', en: 'I am observing through binoculars.' }],
  },
  {
    lt: 'naktinio matymo prietaisas',
    en: 'night-vision device',
    pron: 'nahk-TEE-nyoh MAH-tee-moh pryeh-TIGH-sahs',
    pos: 'phrase',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🌃',
    grammar: 'Often abbreviated in speech to “naktinis”.',
    alt: ['naktinis'],
    examples: [
      { lt: 'Įjunkite naktinio matymo prietaisus.', en: 'Switch on night-vision devices.' },
    ],
  },
  {
    lt: 'kastuvėlis',
    en: 'entrenching tool',
    pron: 'kahs-too-VAY-lis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🛠️',
    grammar: 'Diminutive of “kastuvas” (spade).',
    examples: [{ lt: 'Kask apkasą kastuvėliu.', en: 'Dig the trench with the entrenching tool.' }],
  },
  {
    lt: 'gertuvė',
    en: 'canteen; water bottle',
    pron: 'gehr-too-VAY',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🍶',
    examples: [{ lt: 'Pripildykite gertuves.', en: 'Fill your canteens.' }],
  },
  {
    lt: 'miegmaišis',
    en: 'sleeping bag',
    pron: 'MYEHG-migh-shis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🛏️',
    examples: [{ lt: 'Miegmaišis šlapias.', en: 'The sleeping bag is wet.' }],
  },
  {
    lt: 'palapinė',
    en: 'tent',
    pron: 'pah-lah-pee-NAY',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'equipment',
    emoji: '⛺',
    examples: [{ lt: 'Statome palapines miške.', en: 'We are pitching tents in the forest.' }],
  },
  {
    lt: 'dujokaukė',
    en: 'gas mask; respirator',
    pron: 'DOO-yoh-kow-kay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'equipment',
    emoji: '😷',
    grammar: 'From “dujos” (gas) + “kaukė” (mask).',
    usage: '“Dujos! Dujos! Dujos!” is the alarm call — mask up before you finish hearing it.',
    tags: ['contact'],
    examples: [{ lt: 'Dujos! Užsidėkite dujokaukes!', en: 'Gas! Put on gas masks!' }],
  },
  {
    lt: 'žibintuvėlis',
    en: 'torch; flashlight',
    pron: 'zhee-bin-too-VAY-lis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🔦',
    examples: [{ lt: 'Naudokite raudoną žibintuvėlio šviesą.', en: 'Use the red torch light.' }],
  },
  {
    lt: 'virvė',
    en: 'rope; cord',
    pron: 'VEER-vay',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'equipment',
    emoji: '🪢',
    examples: [{ lt: 'Reikia ilgesnės virvės.', en: 'We need a longer rope.' }],
  },

  // ── Vehicles & supply ─────────────────────────────────────────────────────
  {
    lt: 'transporto priemonė',
    en: 'vehicle',
    pron: 'trahns-POHR-toh PRYEH-moh-nay',
    pos: 'phrase',
    level: 'MIL4',
    category: 'vehicles',
    emoji: '🚙',
    grammar: 'The formal, doctrinal term. Everyday speech says “mašina”.',
    alt: ['mašina'],
    examples: [{ lt: 'Trys transporto priemonės kelyje.', en: 'Three vehicles on the road.' }],
  },
  {
    lt: 'sunkvežimis',
    en: 'truck; lorry',
    pron: 'soonk-VEH-zhee-mis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'vehicles',
    emoji: '🚚',
    examples: [{ lt: 'Sunkvežimis atveš atsargas.', en: 'The truck will bring supplies.' }],
  },
  {
    lt: 'visureigis',
    en: 'off-road vehicle',
    pron: 'vee-soo-RAY-gis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'vehicles',
    emoji: '🚜',
    grammar: 'Literally “goes-everywhere”.',
    examples: [{ lt: 'Visureigis įklimpo.', en: 'The off-road vehicle got stuck.' }],
  },
  {
    lt: 'šarvuotis',
    en: 'armoured vehicle',
    pron: 'shahr-VWOH-tis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'vehicles',
    emoji: '🛡️',
    grammar: 'From “šarvai” (armour).',
    examples: [
      { lt: 'Priešo šarvuotis kvadrate penki du.', en: 'Enemy armoured vehicle in grid five two.' },
    ],
  },
  {
    lt: 'sraigtasparnis',
    en: 'helicopter',
    pron: 'srighg-tahs-PAHR-nis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'vehicles',
    emoji: '🚁',
    grammar: 'From “sraigtas” (screw, propeller) + “sparnas” (wing).',
    examples: [
      {
        lt: 'Sraigtasparnis nusileis už dešimt minučių.',
        en: 'The helicopter will land in ten minutes.',
      },
    ],
  },
  {
    lt: 'bepilotis orlaivis',
    en: 'unmanned aerial vehicle; drone',
    pron: 'beh-pee-LOH-tis OHR-ligh-vis',
    pos: 'phrase',
    level: 'MIL4',
    category: 'vehicles',
    emoji: '🛸',
    grammar: 'Literally “pilotless aircraft”. Everyday speech: “dronas”.',
    alt: ['dronas'],
    examples: [{ lt: 'Virš mūsų bepilotis orlaivis.', en: 'There is a drone above us.' }],
  },
  {
    lt: 'degalai',
    en: 'fuel',
    pron: 'deh-gah-LIGH',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'supply',
    emoji: '⛽',
    grammar: 'Plural only. “Kuras” is the more general word for fuel of any kind.',
    tags: ['plural-only'],
    alt: ['kuras'],
    examples: [{ lt: 'Baigiasi degalai.', en: 'We are running out of fuel.' }],
  },
  {
    lt: 'atsargos',
    en: 'supplies; stocks',
    pron: 'aht-SAHR-gohs',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'supply',
    emoji: '📦',
    grammar: 'Plural in this sense.',
    examples: [{ lt: 'Atsargų užteks dviem paroms.', en: 'Supplies will last two days.' }],
  },
  {
    lt: 'sausas davinys',
    en: 'dry ration; field ration',
    pron: 'SOW-sahs dah-vee-NEES',
    pos: 'phrase',
    level: 'MIL4',
    category: 'supply',
    emoji: '🍱',
    grammar: '“Davinys” alone means a ration or allocation.',
    alt: ['davinys'],
    examples: [{ lt: 'Kiekvienam po du sausus davinius.', en: 'Two dry rations each.' }],
  },
  {
    lt: 'aprūpinimas',
    en: 'supply; logistics',
    pron: 'ah-proo-pee-NEE-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'supply',
    emoji: '🚛',
    examples: [{ lt: 'Aprūpinimas atvyks rytą.', en: 'Resupply will arrive in the morning.' }],
  },

  // ── Ranks ─────────────────────────────────────────────────────────────────
  {
    lt: 'laipsnis',
    en: 'rank (military)',
    pron: 'LIGHPS-nis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '🎖️',
    grammar: 'The same word means “degree” of temperature.',
    examples: [{ lt: 'Koks jūsų laipsnis?', en: 'What is your rank?' }],
  },
  {
    lt: 'eilinis',
    en: 'private',
    pron: 'AY-lee-nis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '🔰',
    grammar: 'Vocative “eilini”. Next step up: “vyresnysis eilinis” (senior private).',
    examples: [{ lt: 'Eilinis Smitas, prie manęs!', en: 'Private Smith, on me!' }],
  },
  {
    lt: 'grandinis',
    en: 'corporal',
    pron: 'grahn-DEE-nis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '🎗️',
    grammar: 'Vocative “grandini”. From “grandis” (a link, a small group).',
    examples: [{ lt: 'Grandinis vadovauja grandžiai.', en: 'The corporal leads the fire team.' }],
  },
  {
    lt: 'puskarininkis',
    en: 'NCO; sergeant',
    pron: 'poos-kah-ree-NEEN-kis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '🎖️',
    grammar:
      'Vocative “puskarininki”. The Lithuanian NCO ladder is built on this word: jaunesnysis puskarininkis, puskarininkis, vyresnysis puskarininkis.',
    usage: 'Address as “pone puskarininki” / “ponia puskarininke”.',
    examples: [{ lt: 'Taip, pone puskarininki!', en: 'Yes, sergeant!' }],
  },
  {
    lt: 'viršila',
    en: 'sergeant major',
    pron: 'veer-SHEE-lah',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '🎖️',
    grammar: 'Grammatically feminine in form but used of men — like “vyriausybė” patterns.',
    examples: [
      {
        lt: 'Kuopos viršila tikrina rikiuotę.',
        en: 'The company sergeant major inspects the formation.',
      },
    ],
  },
  {
    lt: 'leitenantas',
    en: 'lieutenant',
    pron: 'lay-teh-NAHN-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '⭐',
    grammar: 'Vocative “leitenante”. Above him: “vyresnysis leitenantas” (senior lieutenant).',
    examples: [
      { lt: 'Leiskite kreiptis, pone leitenante!', en: 'Permission to speak, lieutenant!' },
    ],
  },
  {
    lt: 'kapitonas',
    en: 'captain',
    pron: 'kah-pee-TOH-nahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '⭐',
    grammar: 'Vocative “kapitone”.',
    examples: [{ lt: 'Kapitonas vadovauja kuopai.', en: 'The captain commands the company.' }],
  },
  {
    lt: 'majoras',
    en: 'major',
    pron: 'mah-YOH-rahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '⭐',
    grammar: 'Vocative “majore”.',
    examples: [{ lt: 'Pranešiu majorui.', en: 'I will report to the major.' }],
  },
  {
    lt: 'pulkininkas',
    en: 'colonel',
    pron: 'pool-kee-NEEN-kahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'ranks',
    emoji: '🌟',
    grammar: 'Vocative “pulkininke”. Below him: “pulkininkas leitenantas” (lieutenant colonel).',
    examples: [
      { lt: 'Pulkininkas atvyko į štabą.', en: 'The colonel has arrived at headquarters.' },
    ],
  },

  // ── Unit structure ────────────────────────────────────────────────────────
  {
    lt: 'skyrius',
    en: 'section; squad',
    pron: 'SKEE-ryoos',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'units',
    emoji: '👥',
    grammar: 'Also means a department or a chapter in civilian use.',
    examples: [{ lt: 'Skyrius pasiruošęs.', en: 'The section is ready.' }],
  },
  {
    lt: 'būrys',
    en: 'platoon',
    pron: 'boo-REES',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'units',
    emoji: '👨‍👨‍👦',
    examples: [{ lt: 'Būrio vadas — leitenantas.', en: 'The platoon commander is a lieutenant.' }],
  },
  {
    lt: 'kuopa',
    en: 'company',
    pron: 'KWOH-pah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'units',
    emoji: '🏛️',
    examples: [
      { lt: 'Kuopa dislokuota poligone.', en: 'The company is deployed at the training area.' },
    ],
  },
  {
    lt: 'batalionas',
    en: 'battalion',
    pron: 'bah-tah-LYOH-nahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'units',
    emoji: '🏰',
    examples: [
      { lt: 'Batalioną sudaro kelios kuopos.', en: 'A battalion is made up of several companies.' },
    ],
  },
  {
    lt: 'brigada',
    en: 'brigade',
    pron: 'bree-GAH-dah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL4',
    category: 'units',
    emoji: '🛡️',
    examples: [
      { lt: 'Mechanizuotoji pėstininkų brigada.', en: 'The mechanised infantry brigade.' },
    ],
  },
  {
    lt: 'štabas',
    en: 'headquarters; staff',
    pron: 'SHTAH-bahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL4',
    category: 'units',
    emoji: '🏢',
    examples: [
      { lt: 'Pranešimas siunčiamas į štabą.', en: 'The report is being sent to headquarters.' },
    ],
  },
];
