import type { Word } from '../types.js';

/**
 * MIL5 — Ryšininkas / Signaller.
 *
 * Radio procedure and reporting: opening and closing a net, acknowledging,
 * asking for a retransmission, and passing a structured situation report.
 *
 * Lithuanian units working inside NATO structures mix these Lithuanian
 * prowords with the standard NATO alphabet and English prowords. What is taught
 * here is the Lithuanian side — see docs/LINGUISTIC_NOTES.md.
 */
export const mil5Words: Word[] = [
  // ── The radio itself ──────────────────────────────────────────────────────
  {
    lt: 'radijo stotis',
    en: 'radio (set)',
    pron: 'RAH-dee-yoh stoh-TIS',
    pos: 'phrase',
    level: 'MIL5',
    category: 'radio',
    emoji: '📻',
    grammar: 'Literally “radio station”. Everyday short form: “stotis”.',
    alt: ['stotis'],
    examples: [{ lt: 'Radijo stotis neveikia.', en: 'The radio is not working.' }],
  },
  {
    lt: 'ryšys',
    en: 'communications; contact; signal',
    pron: 'ree-SHEES',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'radio',
    emoji: '📡',
    grammar: 'Plural “ryšiai” = the communications branch. “Nutrūko ryšys” = comms are lost.',
    tags: ['radio'],
    examples: [{ lt: 'Prastas ryšys, pakartokite.', en: 'Poor comms, say again.' }],
  },
  {
    lt: 'šaukinys',
    en: 'call sign',
    pron: 'show-kee-NEES',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'radio',
    emoji: '🔤',
    grammar: 'From “šaukti” (to call).',
    tags: ['radio'],
    examples: [{ lt: 'Mano šaukinys — Vilkas vienas.', en: 'My call sign is Wolf One.' }],
  },
  {
    lt: 'dažnis',
    en: 'frequency',
    pron: 'DAHZH-nis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'radio',
    emoji: '〰️',
    tags: ['radio'],
    examples: [
      { lt: 'Pereiname į atsarginį dažnį.', en: 'We are switching to the alternate frequency.' },
    ],
  },
  {
    lt: 'ryšio patikra',
    en: 'radio check',
    pron: 'REE-shyoh pah-TEE-krah',
    pos: 'phrase',
    level: 'MIL5',
    category: 'radio',
    emoji: '✔️',
    tags: ['radio'],
    examples: [{ lt: 'Vilkas vienas, ryšio patikra.', en: 'Wolf One, radio check.' }],
  },

  // ── Prowords ──────────────────────────────────────────────────────────────
  {
    lt: 'Priėmiau',
    en: 'Received; Roger',
    pron: 'pree-AY-myow',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '👌',
    grammar: 'Past tense of “priimti” (to receive) — literally “I received”.',
    usage: 'Acknowledges receipt only. If you will also act on it, say “Supratau, vykdau.”',
    tags: ['radio'],
    examples: [{ lt: 'Priėmiau, baigiu.', en: 'Roger, out.' }],
  },
  {
    lt: 'Perduodu',
    en: 'I am passing (a message); transmitting',
    pron: 'per-DWOH-doo',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '📤',
    grammar: '1st person of “perduoti” (to pass on, to transmit).',
    tags: ['radio'],
    examples: [{ lt: 'Perduodu koordinates.', en: 'Passing coordinates.' }],
  },
  {
    lt: 'Kaip girdite?',
    en: 'How do you read me?',
    pron: 'kighp GEER-dee-teh',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '❓',
    grammar: 'Polite plural of “girdėti” (to hear).',
    tags: ['radio'],
    examples: [{ lt: 'Vilkas vienas, kaip girdite?', en: 'Wolf One, how do you read me?' }],
  },
  {
    lt: 'Girdžiu gerai',
    en: 'I read you loud and clear',
    pron: 'GEER-jyoo geh-RIGH',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '🔊',
    grammar: 'Opposite: “girdžiu prastai” (reading you poorly).',
    tags: ['radio'],
    alt: ['girdžiu prastai'],
    examples: [{ lt: 'Girdžiu gerai, perduokite.', en: 'Read you clearly, send.' }],
  },
  {
    lt: 'Laukite',
    en: 'Wait; Standby',
    pron: 'LOW-kee-teh',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '⏸️',
    grammar: 'Polite plural imperative of “laukti”.',
    tags: ['radio'],
    examples: [{ lt: 'Laukite, tikrinu.', en: 'Standby, checking.' }],
  },
  {
    lt: 'Patvirtinkite',
    en: 'Confirm; Acknowledge',
    pron: 'paht-veer-TIN-kee-teh',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '☑️',
    grammar: 'From “patvirtinti” (to confirm). Reply: “Patvirtinu” (I confirm).',
    tags: ['radio'],
    alt: ['patvirtinu'],
    examples: [{ lt: 'Patvirtinkite koordinates.', en: 'Confirm the coordinates.' }],
  },
  {
    lt: 'Teigiamai',
    en: 'Affirmative',
    pron: 'tay-GYAH-migh',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '✅',
    grammar: 'Adverb from “teigiamas” (positive). Clearer on a noisy net than plain “taip”.',
    tags: ['radio'],
    examples: [{ lt: 'Teigiamai, pozicija užimta.', en: 'Affirmative, position occupied.' }],
  },
  {
    lt: 'Neigiamai',
    en: 'Negative',
    pron: 'nay-GYAH-migh',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '⛔',
    grammar: 'Adverb from “neigiamas” (negative). Clearer than plain “ne”.',
    tags: ['radio'],
    examples: [{ lt: 'Neigiamai, priešo nematau.', en: 'Negative, I do not see the enemy.' }],
  },
  {
    lt: 'Baigiu',
    en: 'Out (end of transmission)',
    pron: 'BIGH-gyoo',
    pos: 'phrase',
    level: 'MIL5',
    category: 'prowords',
    emoji: '🔚',
    grammar: '1st person of “baigti” (to finish).',
    tags: ['radio'],
    examples: [{ lt: 'Priėmiau, baigiu.', en: 'Roger, out.' }],
  },
  {
    lt: 'Skubiai',
    en: 'Urgent; immediately',
    pron: 'skoo-BYIGH',
    pos: 'adverb',
    level: 'MIL5',
    category: 'prowords',
    emoji: '🚨',
    grammar: 'From “skubus” (urgent).',
    tags: ['radio'],
    examples: [{ lt: 'Skubiai reikia paramos!', en: 'Urgent — support needed!' }],
  },

  // ── Reporting ─────────────────────────────────────────────────────────────
  {
    lt: 'pranešti',
    en: 'to report; to inform',
    pron: 'prah-NESH-tee',
    pos: 'verb',
    level: 'MIL5',
    category: 'reporting',
    emoji: '📣',
    grammar: 'pranešu, praneši, praneša. The person informed takes the dative: “pranešu vadui”.',
    examples: [{ lt: 'Pranešu apie priešo judėjimą.', en: 'I am reporting enemy movement.' }],
  },
  {
    lt: 'pranešimas',
    en: 'report; message',
    pron: 'prah-neh-SHEE-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'reporting',
    emoji: '📨',
    examples: [{ lt: 'Gavau jūsų pranešimą.', en: 'I received your message.' }],
  },
  {
    lt: 'padėtis',
    en: 'situation; position',
    pron: 'pah-day-TIS',
    pos: 'noun',
    gender: 'f',
    level: 'MIL5',
    category: 'reporting',
    emoji: '🗺️',
    grammar: '“Padėties ataskaita” = situation report (SITREP). Also “situacija”.',
    alt: ['situacija'],
    examples: [{ lt: 'Padėtis kontroliuojama.', en: 'The situation is under control.' }],
  },
  {
    lt: 'stebėti',
    en: 'to observe; to watch',
    pron: 'steh-BAY-tee',
    pos: 'verb',
    level: 'MIL5',
    category: 'reporting',
    emoji: '👁️',
    grammar: 'stebiu, stebi, stebi. “Stebėjimo postas” = observation post.',
    examples: [
      { lt: 'Stebiu kelią iš pozicijos.', en: 'I am observing the road from the position.' },
    ],
  },
  {
    lt: 'pastebėjau',
    en: 'I have spotted; I observed',
    pron: 'pahs-teh-BAY-yow',
    pos: 'verb',
    level: 'MIL5',
    category: 'reporting',
    emoji: '🔍',
    grammar: 'Past of “pastebėti” (to notice, to spot).',
    tags: ['radio'],
    examples: [{ lt: 'Pastebėjau judėjimą miške.', en: 'I have spotted movement in the woods.' }],
  },
  {
    lt: 'priešas',
    en: 'the enemy',
    pron: 'PRYEH-shahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'reporting',
    emoji: '🎯',
    grammar: 'Also used adjectivally in the genitive: “priešo pozicija” = the enemy position.',
    examples: [{ lt: 'Priešas kvadrate keturi vienas.', en: 'Enemy in grid four one.' }],
  },
  {
    lt: 'saviškiai',
    en: 'friendly forces; our own',
    pron: 'sah-VISH-kyigh',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'reporting',
    emoji: '🤝',
    grammar: 'From “savas” (one’s own). Plural.',
    usage: 'Critical before opening fire: “Saviškiai priekyje!” — Friendlies to the front!',
    tags: ['contact'],
    examples: [
      { lt: 'Saviškiai dešinėje, nešaudyti!', en: 'Friendlies on the right, do not fire!' },
    ],
  },
  {
    lt: 'civiliai',
    en: 'civilians',
    pron: 'tsee-VEE-lyigh',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'reporting',
    emoji: '👨‍👩‍👧',
    grammar: 'Singular “civilis”. Note the Lithuanian “c” is pronounced [ts].',
    examples: [{ lt: 'Kaime yra civilių.', en: 'There are civilians in the village.' }],
  },
  {
    lt: 'kiekis',
    en: 'quantity; number of',
    pron: 'KYEH-kis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'reporting',
    emoji: '🔢',
    usage: 'The “size” line of a contact report: “Kiekis — apie dvidešimt.”',
    examples: [{ lt: 'Kiekis — apie dešimt karių.', en: 'Size — about ten soldiers.' }],
  },
  {
    lt: 'vieta',
    en: 'location; place',
    pron: 'VYEH-tah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL5',
    category: 'reporting',
    emoji: '📍',
    examples: [{ lt: 'Vieta — kvadratas trys aštuoni.', en: 'Location — grid three eight.' }],
  },
  {
    lt: 'veiksmas',
    en: 'activity; action',
    pron: 'VAYKS-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'reporting',
    emoji: '⚡',
    usage: 'The “activity” line of a contact report: “Veiksmas — kasa apkasus.”',
    examples: [{ lt: 'Veiksmas — juda į vakarus.', en: 'Activity — moving west.' }],
  },
  {
    lt: 'parama',
    en: 'support',
    pron: 'PAH-rah-mah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL5',
    category: 'requests',
    emoji: '🤲',
    grammar: '“Ugnies parama” = fire support. “Oro parama” = air support.',
    examples: [{ lt: 'Prašau ugnies paramos.', en: 'I request fire support.' }],
  },
  {
    lt: 'pastiprinimas',
    en: 'reinforcement',
    pron: 'pahs-tee-pree-NEE-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'requests',
    emoji: '➕',
    examples: [{ lt: 'Reikia pastiprinimo.', en: 'Reinforcement is needed.' }],
  },
  {
    lt: 'prašau',
    en: 'I request; please',
    pron: 'prah-SHOW',
    pos: 'verb',
    level: 'MIL5',
    category: 'requests',
    emoji: '🙏',
    grammar: '1st person of “prašyti”. What is requested goes in the genitive: “prašau paramos”.',
    tags: ['radio'],
    examples: [{ lt: 'Prašau leidimo judėti.', en: 'I request permission to move.' }],
  },
  {
    lt: 'leidimas',
    en: 'permission; clearance',
    pron: 'lay-DEE-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL5',
    category: 'requests',
    emoji: '🎟️',
    examples: [{ lt: 'Leidimas suteiktas.', en: 'Permission granted.' }],
  },
  {
    lt: 'reikia',
    en: 'it is needed; we need',
    pron: 'RAY-kyah',
    pos: 'verb',
    level: 'MIL5',
    category: 'requests',
    emoji: '❗',
    grammar:
      'Impersonal. The needer takes the dative, the thing needed the genitive: “Mums reikia vandens.”',
    tags: ['dative-subject'],
    examples: [{ lt: 'Mums reikia vandens ir šovinių.', en: 'We need water and ammunition.' }],
  },
];
