import type { Word } from '../types.js';

/**
 * MIL6 — Vadas / Commander.
 *
 * The language of the worst minutes of the day: contact drills, casualty care
 * and evacuation, and the vocabulary needed to give a short set of orders and
 * confirm they were understood.
 */
export const mil6Words: Word[] = [
  // ── Contact drills ────────────────────────────────────────────────────────
  {
    lt: 'Kontaktas!',
    en: 'Contact!',
    pron: 'kohn-TAHK-tahs',
    pos: 'command',
    level: 'MIL6',
    category: 'contact',
    emoji: '💥',
    usage:
      'Always followed by a direction and, if known, a range: “Kontaktas — dešinė, du šimtai!”',
    tags: ['contact'],
    examples: [
      { lt: 'Kontaktas — priekyje, šimtas metrų!', en: 'Contact — front, one hundred metres!' },
    ],
  },
  {
    lt: 'Į priedangą!',
    en: 'Take cover!',
    pron: 'ee pryeh-DAHN-gah',
    pos: 'command',
    level: 'MIL6',
    category: 'contact',
    emoji: '🛡️',
    grammar: 'Preposition “į” + accusative of “priedanga”.',
    tags: ['contact', 'command'],
    examples: [{ lt: 'Į priedangą! Minosvaidžiai!', en: 'Take cover! Mortars!' }],
  },
  {
    lt: 'Perkraunu!',
    en: 'Reloading!',
    pron: 'per-KROW-noo',
    pos: 'command',
    level: 'MIL6',
    category: 'contact',
    emoji: '🔄',
    grammar: '1st person of “perkrauti”. Equally common: “Keičiu apkabą!”',
    usage: 'Shout it so your buddy knows to cover your gap in fire.',
    tags: ['contact'],
    alt: ['keičiu apkabą'],
    examples: [{ lt: 'Perkraunu! Dengk!', en: 'Reloading! Cover me!' }],
  },
  {
    lt: 'Švaru!',
    en: 'Clear!',
    pron: 'SHVAH-roo',
    pos: 'command',
    level: 'MIL6',
    category: 'contact',
    emoji: '✅',
    grammar: 'Impersonal adverb — literally “it is clean”.',
    usage: 'Called on clearing a room, a building or a sector.',
    tags: ['contact'],
    examples: [{ lt: 'Kambarys švaru!', en: 'Room clear!' }],
  },
  {
    lt: 'Nešaudyti!',
    en: 'Do not fire!',
    pron: 'neh-SHOW-dee-tee',
    pos: 'command',
    level: 'MIL6',
    category: 'contact',
    emoji: '🚫',
    grammar:
      'A negated infinitive used as a blunt prohibition — the standard shape for “do not …” orders.',
    tags: ['contact', 'command'],
    examples: [{ lt: 'Nešaudyti! Civiliai!', en: 'Do not fire! Civilians!' }],
  },
  {
    lt: 'Pasitrauk!',
    en: 'Fall back! ; Get back!',
    pron: 'pah-see-TROWK',
    pos: 'command',
    level: 'MIL6',
    category: 'contact',
    emoji: '⬅️',
    grammar: 'Reflexive imperative of “pasitraukti”. Group form: “Pasitraukite!”.',
    tags: ['contact', 'command'],
    alt: ['pasitraukite'],
    examples: [{ lt: 'Pasitraukite prie griovio!', en: 'Fall back to the ditch!' }],
  },
  {
    lt: 'Laikyti poziciją!',
    en: 'Hold the position!',
    pron: 'ligh-KEE-tee poh-ZEE-tsee-yah',
    pos: 'command',
    level: 'MIL6',
    category: 'contact',
    emoji: '🧱',
    grammar: 'Infinitive as an order + accusative “poziciją”.',
    tags: ['command'],
    examples: [
      { lt: 'Laikyti poziciją iki paramos!', en: 'Hold the position until support arrives!' },
    ],
  },
  {
    lt: 'snaiperis',
    en: 'sniper',
    pron: 'SNIGH-peh-ris',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'contact',
    emoji: '🎯',
    usage: 'Called alone as a warning: “Snaiperis!” — get down and out of the open.',
    tags: ['contact'],
    examples: [{ lt: 'Snaiperis! Visi gulk!', en: 'Sniper! Everyone down!' }],
  },
  {
    lt: 'pavojus',
    en: 'danger; threat',
    pron: 'pah-VOH-yoos',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'contact',
    emoji: '⚠️',
    grammar: '“Pavojinga” = it is dangerous.',
    examples: [{ lt: 'Pavojus iš oro!', en: 'Air threat!' }],
  },

  // ── Casualties & first aid ────────────────────────────────────────────────
  {
    lt: 'Medikas!',
    en: 'Medic!',
    pron: 'MEH-dee-kahs',
    pos: 'command',
    level: 'MIL6',
    category: 'medical',
    emoji: '⚕️',
    grammar: 'Also “sanitaras” in older usage.',
    usage: 'Shouted, repeated, and passed down the line until acknowledged.',
    tags: ['contact', 'medical'],
    alt: ['sanitaras'],
    examples: [{ lt: 'Medikas! Sužeistas!', en: 'Medic! Man down!' }],
  },
  {
    lt: 'sužeistas',
    en: 'wounded; injured',
    pron: 'soo-ZHAYS-tahs',
    pos: 'adjective',
    level: 'MIL6',
    category: 'medical',
    emoji: '🩸',
    grammar:
      'Past passive participle of “sužeisti”. Feminine “sužeista”. As a noun: “sužeistasis” = the casualty.',
    alt: ['sužeista', 'sužeistasis'],
    tags: ['medical', 'participle'],
    examples: [{ lt: 'Vienas sužeistas, sąmoningas.', en: 'One casualty, conscious.' }],
  },
  {
    lt: 'žaizda',
    en: 'wound',
    pron: 'zhighz-DAH',
    pos: 'noun',
    gender: 'f',
    level: 'MIL6',
    category: 'medical',
    emoji: '🩹',
    examples: [{ lt: 'Žaizda kairėje kojoje.', en: 'A wound to the left leg.' }],
  },
  {
    lt: 'kraujavimas',
    en: 'bleeding; haemorrhage',
    pron: 'krow-yah-VEE-mahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'medical',
    emoji: '🆘',
    grammar: 'From “kraujas” (blood). “Stabdyti kraujavimą” = to stop the bleeding.',
    tags: ['medical'],
    examples: [{ lt: 'Stiprus kraujavimas!', en: 'Severe bleeding!' }],
  },
  {
    lt: 'turniketas',
    en: 'tourniquet',
    pron: 'toor-nee-KEH-tahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'medical',
    emoji: '🩺',
    tags: ['medical'],
    examples: [{ lt: 'Uždėk turniketą virš žaizdos.', en: 'Apply a tourniquet above the wound.' }],
  },
  {
    lt: 'tvarstis',
    en: 'bandage; dressing',
    pron: 'TVAHRS-tis',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'medical',
    emoji: '🩹',
    grammar: 'Verb “tvarstyti” = to dress a wound.',
    tags: ['medical'],
    examples: [{ lt: 'Reikia švaraus tvarsčio.', en: 'A clean dressing is needed.' }],
  },
  {
    lt: 'pirmoji pagalba',
    en: 'first aid',
    pron: 'peer-MOH-yee pah-GAHL-bah',
    pos: 'phrase',
    level: 'MIL6',
    category: 'medical',
    emoji: '🧰',
    grammar: 'Definite adjective “pirmoji” + “pagalba”.',
    tags: ['medical'],
    examples: [{ lt: 'Suteikiau pirmąją pagalbą.', en: 'I administered first aid.' }],
  },
  {
    lt: 'kvėpuoja',
    en: 'is breathing',
    pron: 'kvay-PWOH-yah',
    pos: 'verb',
    level: 'MIL6',
    category: 'medical',
    emoji: '💨',
    grammar: '3rd person of “kvėpuoti”. Negative: “nekvėpuoja”.',
    tags: ['medical'],
    examples: [{ lt: 'Kvėpuoja, bet be sąmonės.', en: 'Breathing, but unconscious.' }],
  },
  {
    lt: 'be sąmonės',
    en: 'unconscious',
    pron: 'beh SAH-moh-nays',
    pos: 'phrase',
    level: 'MIL6',
    category: 'medical',
    emoji: '😵',
    grammar: 'Preposition “be” (without) + genitive of “sąmonė” (consciousness).',
    tags: ['medical'],
    examples: [{ lt: 'Karys be sąmonės.', en: 'The soldier is unconscious.' }],
  },
  {
    lt: 'neštuvai',
    en: 'stretcher',
    pron: 'nesh-too-VIGH',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'medical',
    emoji: '🛏️',
    grammar: 'Plural only, from “nešti” (to carry).',
    tags: ['plural-only', 'medical'],
    examples: [{ lt: 'Atneškite neštuvus!', en: 'Bring a stretcher!' }],
  },
  {
    lt: 'evakuacija',
    en: 'evacuation',
    pron: 'eh-vah-kwah-TSEE-yah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL6',
    category: 'medical',
    emoji: '🚁',
    grammar: '“Evakuoti” = to evacuate. “Medicininė evakuacija” = medical evacuation.',
    tags: ['medical'],
    examples: [{ lt: 'Prašau skubios evakuacijos.', en: 'I request urgent evacuation.' }],
  },
  {
    lt: 'Gelbėkite!',
    en: 'Help! (distress call)',
    pron: 'GEL-bay-kee-teh',
    pos: 'command',
    level: 'MIL6',
    category: 'medical',
    emoji: '🆘',
    grammar: 'Polite plural imperative of “gelbėti” (to save). “Padėkite!” = help me (assist).',
    alt: ['padėkite'],
    examples: [{ lt: 'Gelbėkite! Žmogus vandenyje!', en: 'Help! Man in the water!' }],
  },

  // ── Orders & briefing ─────────────────────────────────────────────────────
  {
    lt: 'užduotis',
    en: 'mission; task',
    pron: 'oozh-dwoh-TIS',
    pos: 'noun',
    gender: 'f',
    level: 'MIL6',
    category: 'orders',
    emoji: '📋',
    grammar: '“Užduotis įvykdyta” = mission accomplished.',
    examples: [{ lt: 'Mūsų užduotis — stebėti kelią.', en: 'Our mission is to observe the road.' }],
  },
  {
    lt: 'tikslas',
    en: 'objective; aim',
    pron: 'TIKS-lahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'orders',
    emoji: '🎯',
    examples: [{ lt: 'Tikslas — užimti kalvą.', en: 'The objective is to seize the hill.' }],
  },
  {
    lt: 'planas',
    en: 'plan',
    pron: 'PLAH-nahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'orders',
    emoji: '🗒️',
    examples: [{ lt: 'Planas paprastas.', en: 'The plan is simple.' }],
  },
  {
    lt: 'signalas',
    en: 'signal',
    pron: 'sig-NAH-lahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'orders',
    emoji: '🚩',
    grammar: '“Mano signalu” = on my signal (instrumental, no preposition).',
    examples: [{ lt: 'Judame mano signalu.', en: 'We move on my signal.' }],
  },
  {
    lt: 'įsakyti',
    en: 'to order; to command',
    pron: 'ee-sah-KEE-tee',
    pos: 'verb',
    level: 'MIL6',
    category: 'orders',
    emoji: '📢',
    grammar: 'įsakau, įsakai, įsako. The person ordered takes the dative: “įsakau skyriui”.',
    examples: [{ lt: 'Įsakau užimti poziciją.', en: 'I order you to occupy the position.' }],
  },
  {
    lt: 'vykdyti',
    en: 'to execute; to carry out',
    pron: 'VEEK-dee-tee',
    pos: 'verb',
    level: 'MIL6',
    category: 'orders',
    emoji: '⚙️',
    grammar: 'vykdau, vykdai, vykdo. “Įvykdyta!” = completed.',
    examples: [{ lt: 'Užduotis įvykdyta.', en: 'The mission is complete.' }],
  },
  {
    lt: 'užimti',
    en: 'to occupy; to seize',
    pron: 'oo-ZHIM-tee',
    pos: 'verb',
    level: 'MIL6',
    category: 'orders',
    emoji: '🚩',
    grammar: 'užimu, užimi, užima.',
    examples: [{ lt: 'Užimkite pozicijas!', en: 'Occupy your positions!' }],
  },
  {
    lt: 'pozicija',
    en: 'position',
    pron: 'poh-ZEE-tsee-yah',
    pos: 'noun',
    gender: 'f',
    level: 'MIL6',
    category: 'orders',
    emoji: '📌',
    examples: [{ lt: 'Pozicija užimta.', en: 'The position is occupied.' }],
  },
  {
    lt: 'apkasas',
    en: 'trench; fighting position',
    pron: 'AHP-kah-sahs',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'orders',
    emoji: '🕳️',
    grammar: 'From “kasti” (to dig).',
    examples: [{ lt: 'Kaskite apkasus.', en: 'Dig fighting positions.' }],
  },
  {
    lt: 'sektorius',
    en: 'sector; arc of fire',
    pron: 'sek-TOH-ryoos',
    pos: 'noun',
    gender: 'm',
    level: 'MIL6',
    category: 'orders',
    emoji: '🔺',
    examples: [
      {
        lt: 'Tavo sektorius — nuo medžio iki kelio.',
        en: 'Your arc is from the tree to the road.',
      },
    ],
  },

  // ── Team communication ────────────────────────────────────────────────────
  {
    lt: 'Pasiruošę?',
    en: 'Ready? (to a group)',
    pron: 'pah-see-RWOH-shay',
    pos: 'phrase',
    level: 'MIL6',
    category: 'teamwork',
    emoji: '❓',
    grammar: 'Plural of “pasiruošęs”. To one person: “Pasiruošęs?” / “Pasiruošusi?”.',
    examples: [{ lt: 'Pasiruošę? Judam!', en: 'Ready? Let’s move!' }],
  },
  {
    lt: 'Judam!',
    en: 'Let’s move!',
    pron: 'YOO-dahm',
    pos: 'phrase',
    level: 'MIL6',
    category: 'teamwork',
    emoji: '🏃',
    grammar:
      'Clipped form of “judame” (we move). Lithuanian drops the final -e in this colloquial 1st-person-plural “let’s …”.',
    examples: [{ lt: 'Judam, po vieną!', en: 'Let’s move, one at a time!' }],
  },
  {
    lt: 'po vieną',
    en: 'one at a time; in single file',
    pron: 'poh VYEH-nah',
    pos: 'phrase',
    level: 'MIL6',
    category: 'teamwork',
    emoji: '1️⃣',
    grammar: '“Po” + accusative in a distributive sense.',
    examples: [{ lt: 'Kertame kelią po vieną.', en: 'We cross the road one at a time.' }],
  },
  {
    lt: 'kartu',
    en: 'together',
    pron: 'kahr-TOO',
    pos: 'adverb',
    level: 'MIL6',
    category: 'teamwork',
    emoji: '🤝',
    examples: [{ lt: 'Judame kartu.', en: 'We move together.' }],
  },
  {
    lt: 'Laikykis!',
    en: 'Hold on! ; Hang in there!',
    pron: 'ligh-KEE-kis',
    pos: 'command',
    level: 'MIL6',
    category: 'teamwork',
    emoji: '💪',
    grammar: 'Reflexive imperative of “laikytis”. Group form: “Laikykitės!”.',
    usage: 'Said to a casualty while help is on the way.',
    examples: [{ lt: 'Laikykis, medikas jau eina.', en: 'Hang in there, the medic is coming.' }],
  },
  {
    lt: 'Patikrinta',
    en: 'Checked; confirmed',
    pron: 'pah-tee-KREEN-tah',
    pos: 'phrase',
    level: 'MIL6',
    category: 'teamwork',
    emoji: '☑️',
    grammar: 'Neuter past passive participle of “patikrinti”, used impersonally.',
    examples: [{ lt: 'Ginklai patikrinti.', en: 'Weapons checked.' }],
  },
  {
    lt: 'Įvykdyta',
    en: 'Completed; done',
    pron: 'ee-VEEK-dee-tah',
    pos: 'phrase',
    level: 'MIL6',
    category: 'teamwork',
    emoji: '🏁',
    grammar: 'Neuter past passive participle of “įvykdyti”.',
    tags: ['radio'],
    examples: [{ lt: 'Užduotis įvykdyta, grįžtame.', en: 'Task complete, we are returning.' }],
  },
];
