import type { AchievementDef } from './types.js';

/**
 * Achievements. Every one of them is free to earn — there is no paid tier, no
 * boost to buy, and nothing here is time-limited.
 */
export const achievements: AchievementDef[] = [
  // ── First steps ───────────────────────────────────────────────────────────
  {
    slug: 'first-lesson',
    title: 'Pirmoji pamoka',
    description: 'Complete your first lesson.',
    emoji: '🥾',
    metric: 'lessons',
    threshold: 1,
    xpReward: 20,
    tier: 'bronze',
  },
  {
    slug: 'ten-lessons',
    title: 'Naujokų kursas',
    description: 'Complete ten lessons.',
    emoji: '📘',
    metric: 'lessons',
    threshold: 10,
    xpReward: 60,
    tier: 'bronze',
  },
  {
    slug: 'all-lessons',
    title: 'Visas kursas',
    description: 'Complete every lesson in the course.',
    emoji: '🏆',
    metric: 'lessons',
    threshold: 41,
    xpReward: 500,
    tier: 'platinum',
  },

  // ── XP ────────────────────────────────────────────────────────────────────
  {
    slug: 'xp-100',
    title: 'Pirmas šimtas',
    description: 'Earn 100 XP.',
    emoji: '💯',
    metric: 'xp',
    threshold: 100,
    xpReward: 15,
    tier: 'bronze',
  },
  {
    slug: 'xp-1000',
    title: 'Tūkstantis',
    description: 'Earn 1 000 XP.',
    emoji: '⚡',
    metric: 'xp',
    threshold: 1000,
    xpReward: 100,
    tier: 'silver',
  },
  {
    slug: 'xp-5000',
    title: 'Veteranas',
    description: 'Earn 5 000 XP.',
    emoji: '🎖️',
    metric: 'xp',
    threshold: 5000,
    xpReward: 300,
    tier: 'gold',
  },

  // ── Streak ────────────────────────────────────────────────────────────────
  {
    slug: 'streak-3',
    title: 'Trys paros',
    description: 'Train three days in a row.',
    emoji: '🔥',
    metric: 'streak',
    threshold: 3,
    xpReward: 25,
    tier: 'bronze',
  },
  {
    slug: 'streak-7',
    title: 'Savaitė lauke',
    description: 'Train seven days in a row.',
    emoji: '🔥',
    metric: 'streak',
    threshold: 7,
    xpReward: 70,
    tier: 'silver',
  },
  {
    slug: 'streak-30',
    title: 'Mėnesio rotacija',
    description: 'Train thirty days in a row.',
    emoji: '🌟',
    metric: 'streak',
    threshold: 30,
    xpReward: 300,
    tier: 'gold',
  },
  {
    slug: 'streak-100',
    title: 'Šimtas parų',
    description: 'Train one hundred days in a row.',
    emoji: '💎',
    metric: 'streak',
    threshold: 100,
    xpReward: 1000,
    tier: 'platinum',
  },

  // ── Vocabulary ────────────────────────────────────────────────────────────
  {
    slug: 'words-25',
    title: 'Pirmi žodžiai',
    description: 'Learn 25 words.',
    emoji: '📖',
    metric: 'words',
    threshold: 25,
    xpReward: 25,
    tier: 'bronze',
  },
  {
    slug: 'words-100',
    title: 'Šimtas žodžių',
    description: 'Learn 100 words.',
    emoji: '📚',
    metric: 'words',
    threshold: 100,
    xpReward: 100,
    tier: 'silver',
  },
  {
    slug: 'words-250',
    title: 'Žodynas',
    description: 'Learn 250 words.',
    emoji: '🧠',
    metric: 'words',
    threshold: 250,
    xpReward: 250,
    tier: 'gold',
  },

  // ── Skill-specific ────────────────────────────────────────────────────────
  {
    slug: 'speak-25',
    title: 'Balsas',
    description: 'Pass 25 speaking exercises.',
    emoji: '🎙️',
    metric: 'speaking',
    threshold: 25,
    xpReward: 60,
    tier: 'silver',
  },
  {
    slug: 'speak-100',
    title: 'Garsiai ir aiškiai',
    description: 'Pass 100 speaking exercises.',
    emoji: '📢',
    metric: 'speaking',
    threshold: 100,
    xpReward: 200,
    tier: 'gold',
  },
  {
    slug: 'listen-50',
    title: 'Ausys',
    description: 'Pass 50 listening exercises.',
    emoji: '👂',
    metric: 'listening',
    threshold: 50,
    xpReward: 80,
    tier: 'silver',
  },
  {
    slug: 'write-50',
    title: 'Raštininkas',
    description: 'Pass 50 writing exercises.',
    emoji: '✍️',
    metric: 'writing',
    threshold: 50,
    xpReward: 80,
    tier: 'silver',
  },
  {
    slug: 'perfect-5',
    title: 'Be klaidų',
    description: 'Finish five lessons without a single mistake.',
    emoji: '🎯',
    metric: 'perfect_lessons',
    threshold: 5,
    xpReward: 100,
    tier: 'silver',
  },
  {
    slug: 'perfect-25',
    title: 'Snaiperio tikslumas',
    description: 'Finish twenty-five lessons without a single mistake.',
    emoji: '🏹',
    metric: 'perfect_lessons',
    threshold: 25,
    xpReward: 350,
    tier: 'gold',
  },
  {
    slug: 'accuracy-90',
    title: 'Tikslumas 90 %',
    description: 'Hold a 90 % lifetime accuracy over at least 200 answers.',
    emoji: '📈',
    metric: 'accuracy',
    threshold: 90,
    xpReward: 200,
    tier: 'gold',
  },

  // ── Progression ───────────────────────────────────────────────────────────
  {
    slug: 'level-2',
    title: 'Kareivis',
    description: 'Reach military level 2.',
    emoji: '🪖',
    metric: 'level',
    threshold: 2,
    xpReward: 50,
    tier: 'bronze',
  },
  {
    slug: 'level-4',
    title: 'Specialistas',
    description: 'Reach military level 4.',
    emoji: '⚙️',
    metric: 'level',
    threshold: 4,
    xpReward: 150,
    tier: 'silver',
  },
  {
    slug: 'level-6',
    title: 'Vadas',
    description: 'Reach military level 6.',
    emoji: '⭐',
    metric: 'level',
    threshold: 6,
    xpReward: 400,
    tier: 'platinum',
  },
];
