import type { GrammarPage } from './types.js';

/**
 * Standalone grammar reference. These pages are browsable at any time from the
 * Grammar tab; the shorter briefings attached to individual lessons in units.ts
 * teach the same points in context.
 */
export const grammarPages: GrammarPage[] = [
  {
    slug: 'tarimas',
    title: 'Pronunciation',
    level: 'MIL1',
    order: 1,
    summary: 'Lithuanian is written as it sounds. Learn six letters and you can read anything.',
    body: [
      '## One letter, one sound',
      '',
      'Lithuanian spelling is almost perfectly phonemic. Once you know the alphabet you can pronounce a word you have never seen — including a place name or a call sign coming over a noisy net.',
      '',
      '## The six that matter',
      '',
      '| Letter | Sound | Example |',
      '| --- | --- | --- |',
      '| **š** | *sh* in "ship" | **š**autuvas — rifle |',
      '| **ž** | *zh* in "measure" | **ž**emėlapis — map |',
      '| **č** | *ch* in "church" | a**č**iū — thank you |',
      '| **ė** | tight *ay*, no glide | d**ė**mesio — attention |',
      '| **ū** | long *oo* | b**ū**rys — platoon |',
      '| **j** | *y* in "yes" | **j**ūs — you |',
      '',
      '## Three traps for English speakers',
      '',
      '1. **y** is a **vowel** — a long *ee*. Never the *y* of "yes"; that job belongs to **j**.',
      '2. **c** is always *ts*. *civiliai* is **tsee-VEE-lyigh**.',
      '3. The nasal letters **ą ę į ų** are no longer nasal. They just mark a long vowel — and often a grammatical ending.',
      '',
      '## Diphthongs',
      '',
      '| Spelling | Sound | Example |',
      '| --- | --- | --- |',
      '| ai | *eye* | k**ai**rė — left |',
      '| ei | *ay* | **ei**lė — rank |',
      '| au | *ow* | l**au**kas — field |',
      '| ie | *yeh* | pr**ie**šas — enemy |',
      '| uo | *woh* | d**uo**ti — to give |',
      '',
      '## Stress',
      '',
      'Lithuanian stress is **mobile** — it can shift between forms of the same word (*vanduõ* → *vandeñs*) — and it carries pitch. Kalba marks the stressed syllable in CAPITALS in the respelling for each word, but do not let stress paralyse you: word order and endings carry the meaning, and you will be understood long before your stress is native.',
    ].join('\n'),
  },
  {
    slug: 'kreipinys',
    title: 'Address & the vocative',
    level: 'MIL1',
    order: 2,
    summary:
      'The case used only for calling someone. Getting it wrong sounds like insubordination.',
    body: [
      '## A case English lost',
      '',
      'When you speak **to** someone, Lithuanian puts their name and rank into the **vocative** (šauksmininkas). Using the dictionary form instead sounds like you are talking *about* them to someone else.',
      '',
      '| Dictionary form | Vocative | Meaning |',
      '| --- | --- | --- |',
      '| ponas | **pone** | sir |',
      '| kapitonas | **kapitone** | captain |',
      '| leitenantas | **leitenante** | lieutenant |',
      '| majoras | **majore** | major |',
      '| pulkininkas | **pulkininke** | colonel |',
      '| vadas | **vade** | commander |',
      '| puskarininkis | **puskarininki** | sergeant |',
      '| eilinis | **eilini** | private |',
      '| Smitas | **Smitai** | Smith |',
      '',
      '## The rule',
      '',
      '- ending **-as** → **-e**  (kapitonas → kapitone)',
      '- ending **-is** → **-i**  (puskarininkis → puskarininki)',
      '- surnames in **-as** → **-ai** (Smitas → Smitai)',
      '',
      'Both words change. It is *pone kapitone*, never *ponas kapitone*.',
      '',
      '## To a woman',
      '',
      '**Ponia** does not change form, but the rank still does: *ponia kapitone*, *ponia majore*.',
      '',
      '## Three answers',
      '',
      '| Say | When |',
      '| --- | --- |',
      '| **Klausau!** | your name has been called; answering a field telephone |',
      '| **Supratau!** | you have understood the content — *roger* |',
      '| **Vykdau!** | understood **and** complying — *wilco* |',
    ].join('\n'),
  },
  {
    slug: 'liepiamoji-nuosaka',
    title: 'Commands & the imperative',
    level: 'MIL1',
    order: 3,
    summary: 'Commands are imperatives, not infinitives. Drop -ti, add -k or -kite.',
    body: [
      '## Never shout the dictionary form',
      '',
      'A Lithuanian command is an **imperative** (*liepiamoji nuosaka*). Word lists give you *stoti*, *gulti*, *eiti* — those are **infinitives**, the form you look up. Nobody shouts them.',
      '',
      '| Infinitive | To one person | To several |',
      '| --- | --- | --- |',
      '| stoti (to stand/stop) | **Stok!** | **Stokite!** |',
      '| gulti (to lie down) | **Gulk!** | **Gulkite!** |',
      '| sekti (to follow) | **Sek!** | **Sekite!** |',
      '| pakartoti (to repeat) | **Pakartok!** | **Pakartokite!** |',
      '| dengti (to cover) | **Dengk!** | **Dengkite!** |',
      '',
      '**Rule:** drop **-ti**, add **-k** (one) or **-kite** (several).',
      '',
      '## Reflexive verbs',
      '',
      'Verbs ending in **-tis** keep their reflexive tail:',
      '',
      '| Infinitive | One | Several |',
      '| --- | --- | --- |',
      '| keltis (to get up) | **Kelkis!** | **Kelkitės!** |',
      '| slėptis (to take cover) | **Slėpkis!** | **Slėpkitės!** |',
      '| rikiuotis (to form up) | **Rikiuokis!** | **Rikiuokitės!** |',
      '| pasitraukti (to fall back) | **Pasitrauk!** | **Pasitraukite!** |',
      '',
      '## Orders to a group: the bare infinitive',
      '',
      'For a whole formation under stress, Lithuanian often uses the **plain infinitive**. It is short, impersonal, and does not force you to choose singular or plural:',
      '',
      '- **Nešaudyti!** — Do not fire!',
      '- **Nutraukti ugnį!** — Cease fire!',
      '- **Laikyti poziciją!** — Hold the position!',
      '- **Trauktis!** — Withdraw!',
      '',
      '## Words that are commands without being verbs',
      '',
      '**Ramiai!** (attention), **Laisvai!** (at ease), **Pirmyn!** (forward), **Greičiau!** (faster), **Tyliai!** (quiet), **Dešinėn!** (right face) are adverbs and case-forms pressed into service as commands.',
      '',
      '## The one to get right',
      '',
      '**Ramiai!** brings a formation to attention. **Dėmesio!** means "pay attention, listen up" and appears on hazard signs. They are not interchangeable.',
    ].join('\n'),
  },
  {
    slug: 'esamasis-laikas',
    title: 'Present tense',
    level: 'MIL2',
    order: 4,
    summary: 'Six endings. The ending tells you who is acting, so the pronoun is usually dropped.',
    body: [
      '## Endings do the work',
      '',
      'Because the verb ending already identifies the person, Lithuanian normally drops the pronoun. **Judu!** is a complete sentence: "I am moving!"',
      '',
      '| | judėti (move) | dengti (cover) | stebėti (observe) |',
      '| --- | --- | --- | --- |',
      '| aš | jud**u** | deng**iu** | steb**iu** |',
      '| tu | jud**i** | deng**i** | steb**i** |',
      '| jis / ji | jud**a** | deng**ia** | steb**i** |',
      '| mes | jud**ame** | deng**iame** | steb**ime** |',
      '| jūs | jud**ate** | deng**iate** | steb**ite** |',
      '| jie / jos | jud**a** | deng**ia** | steb**i** |',
      '',
      '## No “am / is / are”, no continuous',
      '',
      'One present tense covers both English forms. **Judu** = "I move" *and* "I am moving". There is no auxiliary verb to add.',
      '',
      '## “To be” is irregular — and often omitted',
      '',
      '| | būti |',
      '| --- | --- |',
      '| aš | **esu** |',
      '| tu | **esi** |',
      '| jis / ji | **yra** |',
      '| mes | **esame** |',
      '| jūs | **esate** |',
      '| jie / jos | **yra** |',
      '',
      'In the present it is frequently dropped altogether: *Skyrius pasiruošęs* — "The section [is] ready." *Priešas miške* — "The enemy [is] in the woods."',
      '',
      '## Negation',
      '',
      'Attach **ne-** to the front of the verb — one word, no space:',
      '',
      '- suprantu → **ne**suprantu (I don’t understand)',
      '- matau → **ne**matau (I don’t see)',
      '- kvėpuoja → **ne**kvėpuoja (is not breathing)',
    ].join('\n'),
  },
  {
    slug: 'linksniai',
    title: 'The seven cases',
    level: 'MIL2',
    order: 5,
    summary: 'Lithuanian marks a noun’s job with an ending, not with word order.',
    body: [
      '## Why this matters more than word order',
      '',
      'English fixes meaning by position: *the enemy sees the soldier* ≠ *the soldier sees the enemy*. Lithuanian fixes it with **endings**, so word order is free and used for emphasis instead.',
      '',
      '## The full set, on one word',
      '',
      '**žemėlapis** — map',
      '',
      '| Case | Form | Job | Example |',
      '| --- | --- | --- | --- |',
      '| Nominative | žemėlapi**s** | the subject | *Žemėlapis čia.* |',
      '| Genitive | žemėlapi**o** | of / possession / after many words | *Žemėlapio mastelis.* |',
      '| Dative | žemėlapi**ui** | to / for | *Duok žemėlapiui vietos.* |',
      '| Accusative | žemėlap**į** | the direct object | *Duok žemėlapį.* |',
      '| Instrumental | žemėlapi**u** | by / with (means) | *Orientuojuosi žemėlapiu.* |',
      '| Locative | žemėlapy**je** | in / on | *Pažymėk žemėlapyje.* |',
      '| Vocative | žemėlapi | calling out to | — |',
      '',
      '## The four you must have first',
      '',
      '**Nominative** — the dictionary form, the subject.',
      '',
      '**Accusative** — the direct object. *Užimkite pozicij**ą***. Also after motion prepositions: *į priedang**ą***, *per up**ę***.',
      '',
      '**Genitive** — the busiest case in the language. Possession (*būri**o** vadas*), what you ask for (*prašau param**os***), what you need (*reikia vand**ens***), after *už*, *prie*, *tarp*, *iki*, *be*, and after numbers from five up (*dešimt kari**ų***).',
      '',
      '**Locative** — where something is, with **no preposition at all**: *mišk**e*** (in the woods), *kvadrat**e*** (in the grid square), *pozicij**oje*** (in position).',
      '',
      '## Reading a contact report through the cases',
      '',
      '> *Priešas kvadrate keturi du juda į vakarus.*',
      '',
      '- **priešas** — nominative: he is the subject',
      '- **kvadrate** — locative: that is where he is',
      '- **į vakarus** — accusative after *į*: that is where he is heading',
    ].join('\n'),
  },
  {
    slug: 'prielinksniai',
    title: 'Prepositions & the case they take',
    level: 'MIL2',
    order: 6,
    summary: 'Every preposition rules a case. Learn the pair, not the word.',
    body: [
      '## Learn them in pairs',
      '',
      'A Lithuanian preposition forces a case on the noun that follows. Memorising *už* without *+ genitive* leaves you unable to use it.',
      '',
      '| Preposition | Case | Meaning | Example |',
      '| --- | --- | --- | --- |',
      '| **į** | accusative | into, to | *į priedang**ą*** |',
      '| **per** | accusative | across, through | *per up**ę*** |',
      '| **aplink** | accusative | around | *aplink pastat**ą*** |',
      '| **prieš** | accusative | before, against | *prieš aušr**ą*** |',
      '| **už** | genitive | behind, beyond | *už tilt**o*** |',
      '| **prie** | genitive | at, by, near | *prie kel**io*** |',
      '| **tarp** | genitive | between, among | *tarp med**žių*** |',
      '| **iki** | genitive | until, as far as | *iki vidurnakč**io*** |',
      '| **be** | genitive | without | *be sąmon**ės*** |',
      '| **nuo** | genitive | from | *nuo med**žio*** |',
      '| **su** | instrumental | with (accompanying) | *su vad**u*** |',
      '| **po** | instrumental | under | *po tilt**u*** |',
      '',
      '## Motion versus location',
      '',
      'The same idea splits by case:',
      '',
      '| | Motion (going there) | Location (being there) |',
      '| --- | --- | --- |',
      '| right | **į dešinę** | **dešinėje** |',
      '| north | **į šiaurę** | **šiaurėje** |',
      '| the woods | **į mišką** | **miške** |',
      '| position | **į poziciją** | **pozicijoje** |',
      '',
      'A movement order takes the motion form: *Judam į dešinę!*',
      'A contact report takes the location form: *Priešas dešinėje!*',
      '',
      '## Location needs no preposition',
      '',
      'The locative ending alone means "in" or "at". *Priešas miške* is complete — no word for "in", no verb for "is".',
    ].join('\n'),
  },
  {
    slug: 'butasis-laikas',
    title: 'Past tense',
    level: 'MIL5',
    order: 7,
    summary: 'Two patterns. Learn the third-person form and the rest follows.',
    body: [
      '## Two families',
      '',
      'Every Lithuanian verb forms its simple past in one of two patterns. Which one is not predictable from the infinitive alone, so learn the **3rd person past** together with the infinitive — everything else is mechanical from there.',
      '',
      '### The -o family',
      '',
      '| | dirbti → dirb**o** |',
      '| --- | --- |',
      '| aš | dirb**au** |',
      '| tu | dirb**ai** |',
      '| jis / ji | dirb**o** |',
      '| mes | dirb**ome** |',
      '| jūs | dirb**ote** |',
      '| jie / jos | dirb**o** |',
      '',
      '### The -ė family',
      '',
      '| | matyti → mat**ė** |',
      '| --- | --- |',
      '| aš | mač**iau** |',
      '| tu | mat**ei** |',
      '| jis / ji | mat**ė** |',
      '| mes | mat**ėme** |',
      '| jūs | mat**ėte** |',
      '| jie / jos | mat**ė** |',
      '',
      '## The ones you will actually use',
      '',
      '| Infinitive | 3rd person past | “I …” |',
      '| --- | --- | --- |',
      '| būti | buvo | **buvau** |',
      '| atvykti | atvyko | **atvykau** |',
      '| suprasti | suprato | **supratau** |',
      '| priimti | priėmė | **priėmiau** |',
      '| pastebėti | pastebėjo | **pastebėjau** |',
      '| matyti | matė | **mačiau** |',
      '| eiti | ėjo | **ėjau** |',
      '',
      'Three of these are prowords in their own right: **Supratau** (roger), **Priėmiau** (received), **Pastebėjau** (I have spotted).',
      '',
      '## Verbs in -ėti',
      '',
      'They insert **-ėj-**: turėti → tur**ėjo**, tur**ėjau**; stebėti → steb**ėjo**, steb**ėjau**.',
    ].join('\n'),
  },
  {
    slug: 'dalyviai',
    title: 'Participles in reports',
    level: 'MIL6',
    order: 8,
    summary: 'Lithuanian loves participles. You need three of them to read a status report.',
    body: [
      '## Why a beginner meets participles early',
      '',
      'Lithuanian has an unusually rich participle system, and status reports are built out of it. You will meet these long before you would in a civilian course.',
      '',
      '## The passive participle: “it has been done”',
      '',
      'Formed from the verb, agreeing in gender and number. This is how you report a state:',
      '',
      '| Verb | Participle | Report |',
      '| --- | --- | --- |',
      '| užimti (occupy) | **užimta** | *Pozicija užimta.* — Position occupied. |',
      '| patikrinti (check) | **patikrinti** | *Ginklai patikrinti.* — Weapons checked. |',
      '| įvykdyti (execute) | **įvykdyta** | *Užduotis įvykdyta.* — Task complete. |',
      '| sunaikinti (destroy) | **sunaikintas** | *Tiltas sunaikintas.* — The bridge is destroyed. |',
      '| užminuoti (mine) | **užminuotas** | *Kelias užminuotas.* — The road is mined. |',
      '| sužeisti (wound) | **sužeistas** | *Vienas sužeistas.* — One casualty. |',
      '',
      'Note the neuter **-a** form (*užimta*, *įvykdyta*, *patikrinta*) used impersonally — this is the standard shape of a completion report.',
      '',
      '## Agreement',
      '',
      '**Sužeistas** changes with who is hurt:',
      '',
      '- *sužeist**as*** — one man',
      '- *sužeist**a*** — one woman',
      '- *sužeist**i*** — several',
      '',
      '## The active participle: “the one who is …”',
      '',
      '- **dirbantis** — working, the one who works',
      '- **pasiruošęs** — ready (having prepared)',
      '- **pavargęs** — tired (having tired)',
      '',
      '*Skyrius pasiruošęs* — "The section is ready."',
      '',
      '## The half-participle: “while …”',
      '',
      'Same subject as the main verb, and it agrees:',
      '',
      '> *Stebėdamas kelią, pastebėjau judėjimą.*',
      '> While observing the road, I spotted movement.',
      '',
      'Different subject — use the **-ant** form instead:',
      '',
      '> *Mums judant, priešas atidengė ugnį.*',
      '> As we were moving, the enemy opened fire.',
    ].join('\n'),
  },
];
