import type { Unit } from './types.js';

/**
 * The Military Lithuanian syllabus: 19 units across 6 levels.
 *
 * Each lesson lists the vocabulary it introduces (by `Word.lt`) plus
 * sentence-level drills. `buildLesson()` in build.ts expands those into the
 * concrete exercises the player renders, so the syllabus stays readable and a
 * single change to the generator improves every lesson at once.
 */
export const units: Unit[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // MIL1 — Naujokas / Recruit
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'pirmoji-diena',
    title: 'Pirmoji diena',
    description: 'First day: the sounds English speakers get wrong, and how to address a superior.',
    emoji: '🫡',
    level: 'MIL1',
    color: '#4ade80',
    lessons: [
      {
        slug: 'garsai',
        title: 'Garsai',
        subtitle: 'Six letters that change meaning',
        emoji: '🔤',
        words: ['š', 'ž', 'č', 'ė', 'j', 'ū'],
        grammar: {
          title: 'Lithuanian is written as it sounds',
          body: [
            'Lithuanian spelling is close to one-letter-one-sound, so once you know the alphabet you can read any word aloud — including one you have never seen. That matters when a grid reference or a place name comes over the radio.',
            '',
            'Six letters do not exist in English and are worth an hour of your time:',
            '',
            '| Letter | Sound | In the field |',
            '| --- | --- | --- |',
            '| **š** | *sh* in "ship" | **š**autuvas — rifle |',
            '| **ž** | *zh* in "measure" | **ž**emėlapis — map |',
            '| **č** | *ch* in "church" | a**č**iū — thank you |',
            '| **ė** | tight *ay*, no glide | dė**mesio** — attention |',
            '| **ū** | long *oo* | b**ū**rys — platoon |',
            '| **j** | *y* in "yes" | **j**ūs — you |',
            '',
            'Two traps. Lithuanian **y** is a long *ee* vowel, never a consonant. And **c** is always *ts* — "civiliai" is *tsee-VEE-lyigh*, not *sih-VIL-yai*.',
          ].join('\n'),
        },
        drills: [
          { lt: 'šautuvas', en: 'a rifle', modes: ['listen_type', 'speak'] },
          { lt: 'žemėlapis', en: 'a map', modes: ['listen_type', 'speak'] },
          { lt: 'būrys', en: 'a platoon', modes: ['listen_type', 'speak'] },
        ],
        xp: 10,
      },
      {
        slug: 'kreipinys',
        title: 'Kreipinys',
        subtitle: 'Sir, ma’am, and the vocative case',
        emoji: '🎖️',
        words: ['ponas', 'ponia', 'laba diena', 'ačiū', 'atsiprašau', 'taip', 'ne'],
        grammar: {
          title: 'The vocative — the case for calling someone',
          body: [
            'Lithuanian has a dedicated case used only when you address someone directly. English lost it; you cannot skip it here, because using the plain dictionary form to a superior sounds like you are talking *about* them.',
            '',
            '| Rank (dictionary) | Address form |',
            '| --- | --- |',
            '| ponas | **pone** |',
            '| kapitonas | **kapitone** |',
            '| leitenantas | **leitenante** |',
            '| majoras | **majore** |',
            '| puskarininkis | **puskarininki** |',
            '| eilinis | **eilini** |',
            '',
            'The pattern: **-as → -e**, **-is → -i**. Both words change: *pone kapitone*, not *ponas kapitone*.',
            '',
            'To a woman: **ponia** does not change, but the rank still does — *ponia kapitone*.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Laba diena, pone kapitone.', en: 'Good afternoon, captain.' },
          { lt: 'Ačiū, pone leitenante.', en: 'Thank you, lieutenant.' },
          {
            lt: 'Atsiprašau, ponia majore.',
            en: 'My apologies, major.',
            blank: 'majore',
            explanation: 'Vocative of “majoras”: -as → -e.',
          },
        ],
        xp: 15,
      },
      {
        slug: 'atsakymai',
        title: 'Atsakymai',
        subtitle: 'Answering: yes, understood, carrying it out',
        emoji: '👂',
        words: ['klausau', 'supratau', 'vykdau', 'aišku', 'nesuprantu', 'pakartokite', 'lėčiau'],
        grammar: {
          title: 'Three answers, three meanings',
          body: [
            'English "yes sir" covers a lot of ground. Lithuanian splits it, and the distinction is doctrinal, not stylistic:',
            '',
            '- **Klausau!** — "I am listening." Your answer when a superior calls your name, and how you answer a field telephone.',
            '- **Supratau!** — "I understood." Acknowledges the *content* of an order or message. This is the Lithuanian *roger*.',
            '- **Vykdau!** — "I am carrying it out." Understood **and** complying. This is *wilco*.',
            '',
            'Never guess. **Nesuprantu** ("I don’t understand") followed by **Pakartokite** ("say again") costs three seconds; a misheard order costs more.',
            '',
            'Notice the negation: **ne-** simply attaches to the front of the verb. suprantu → **ne**suprantu, šaudyti → **ne**šaudyti.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Supratau, pone vade!', en: 'Understood, commander!' },
          { lt: 'Vykdau!', en: 'Carrying it out!', modes: ['speak', 'listen_type'] },
          {
            lt: 'Atsiprašau, nesuprantu. Pakartokite, prašau.',
            en: 'Sorry, I don’t understand. Say again, please.',
          },
          {
            lt: 'Kalbėkite lėčiau, prašau.',
            en: 'Please speak more slowly.',
            blank: 'lėčiau',
          },
        ],
        xp: 15,
      },
      {
        slug: 'prisistatymas',
        title: 'Prisistatymas',
        subtitle: 'Reporting in',
        emoji: '📋',
        words: [
          'leiskite kreiptis',
          'atvykau',
          'įsakymas',
          'pasiruošęs',
          'karys',
          'vadas',
          'kariuomenė',
        ],
        grammar: {
          title: 'Reporting in',
          body: [
            'The formal report has a fixed shape. Learn it as one block:',
            '',
            '> **Eilinis Smitas pagal jūsų įsakymą atvyko!**',
            '> *Private Smith reporting as ordered!*',
            '',
            'Rank + surname + "as per your order" + "has arrived". Note that you refer to yourself in the **third person** — *atvyko* (he/she arrived), not *atvykau* (I arrived). Speaking of yourself as "the soldier" is standard in the Lithuanian report.',
            '',
            'To open a conversation with a superior first: **Leiskite kreiptis, pone kapitone!**',
          ].join('\n'),
        },
        drills: [
          { lt: 'Leiskite kreiptis, pone kapitone!', en: 'Permission to speak, captain!' },
          {
            lt: 'Eilinis Smitas pagal jūsų įsakymą atvyko!',
            en: 'Private Smith reporting as ordered!',
          },
          { lt: 'Skyrius pasiruošęs.', en: 'The section is ready.' },
          { lt: 'Įsakymas aiškus.', en: 'The order is clear.' },
        ],
        xp: 20,
      },
    ],
  },
  {
    slug: 'pirmieji-isakymai',
    title: 'Pirmieji įsakymai',
    description: 'The commands you will hear in your first hour on the ground.',
    emoji: '📢',
    level: 'MIL1',
    color: '#22c55e',
    lessons: [
      {
        slug: 'ramiai-laisvai',
        title: 'Ramiai, laisvai',
        subtitle: 'Attention and at ease',
        emoji: '🧍',
        words: ['Ramiai!', 'Laisvai!', 'Dėmesio!'],
        grammar: {
          title: '“Ramiai!” is attention — “Dėmesio!” is not',
          body: [
            'This one trips up every English speaker, because both translate as "attention".',
            '',
            '- **Ramiai!** — the drill command. Heels together, arms at your sides. Literally "calmly".',
            '- **Laisvai!** — at ease. Literally "freely".',
            '- **Dėmesio!** — "pay attention", "listen up", "caution". It opens an announcement or a radio message, and it is what you read on a hazard sign. It will **not** bring a formation to attention.',
            '',
            'The unit name comes first, the command second: *Būrys — ramiai!*',
          ].join('\n'),
        },
        drills: [
          {
            lt: 'Būrys, ramiai!',
            en: 'Platoon, attention!',
            modes: ['listen_select', 'word_bank'],
          },
          {
            lt: 'Skyrius, laisvai!',
            en: 'Section, at ease!',
            modes: ['listen_select', 'word_bank'],
          },
          { lt: 'Dėmesio! Klausykite įsakymo.', en: 'Attention! Listen to the order.' },
        ],
        extraExercises: [
          {
            type: 'react',
            prompt: 'Ramiai!',
            instruction: 'What do you do?',
            audioText: 'Ramiai!',
            answer: 'Come to attention',
            options: ['Come to attention', 'Relax your stance', 'Take cover', 'Start marching'],
            explanation: '“Ramiai!” is the Lithuanian drill command for the position of attention.',
            difficulty: 2,
          },
          {
            type: 'react',
            prompt: 'Dėmesio!',
            instruction: 'What do you do?',
            audioText: 'Dėmesio!',
            answer: 'Stop and listen — something follows',
            options: [
              'Stop and listen — something follows',
              'Come to attention',
              'Fall out',
              'Open fire',
            ],
            explanation:
              '“Dėmesio!” warns you that a message or a hazard follows. The attention command is “Ramiai!”.',
            difficulty: 2,
          },
        ],
        xp: 15,
      },
      {
        slug: 'judejimo-komandos',
        title: 'Judėjimo komandos',
        subtitle: 'Halt, move, down, up',
        emoji: '🏃',
        words: ['Stok!', 'Pirmyn!', 'Gulk!', 'Kelkis!', 'Sek mane!'],
        grammar: {
          title: 'Commands are imperatives, never infinitives',
          body: [
            'A Lithuanian command uses the **imperative**. Textbook lists that give you *stoti*, *eiti*, *gulėti* are showing you the dictionary form — nobody shouts those.',
            '',
            '| Infinitive (dictionary) | Command (to one) | Command (to several) |',
            '| --- | --- | --- |',
            '| stoti | **Stok!** | **Stokite!** |',
            '| gulti | **Gulk!** | **Gulkite!** |',
            '| keltis | **Kelkis!** | **Kelkitės!** |',
            '| sekti | **Sek!** | **Sekite!** |',
            '',
            'The pattern: drop the infinitive **-ti** and add **-k** for one person, **-kite** for several. Reflexive verbs keep their **-is / -itės** ending.',
            '',
            '**Pirmyn!** is not a verb at all — it is the adverb "forward", used on its own as a command.',
            '',
            'Sentry challenge worth memorising now: **Stok! Kas eina?** — "Halt! Who goes there?"',
          ].join('\n'),
        },
        drills: [
          { lt: 'Stok! Kas eina?', en: 'Halt! Who goes there?' },
          { lt: 'Skyrius, pirmyn!', en: 'Section, move!' },
          { lt: 'Gulk! Į priedangą!', en: 'Get down! Take cover!' },
          { lt: 'Kelkitės, judam!', en: 'On your feet, let’s move!' },
          { lt: 'Sekite mane, po vieną!', en: 'Follow me, one at a time!' },
        ],
        extraExercises: [
          {
            type: 'react',
            prompt: 'Gulk!',
            instruction: 'What do you do?',
            audioText: 'Gulk!',
            answer: 'Get down on the ground',
            options: [
              'Get down on the ground',
              'Stand up',
              'Halt where you are',
              'Follow the commander',
            ],
            difficulty: 2,
          },
          {
            type: 'select',
            prompt: 'Which form would actually be shouted as a command?',
            answer: 'Stok!',
            options: ['Stok!', 'Stoti!', 'Stojimas!', 'Stovi!'],
            explanation:
              'The imperative “Stok!” is the command. “Stoti” is the infinitive — the dictionary form.',
            difficulty: 2,
          },
        ],
        xp: 20,
      },
      {
        slug: 'tempas-ir-tyla',
        title: 'Tempas ir tyla',
        subtitle: 'Faster, quieter',
        emoji: '🤫',
        words: ['Greičiau!', 'Tyliai!', 'kareivinės', 'poligonas', 'sargyba', 'postas'],
        drills: [
          { lt: 'Greičiau, kariai!', en: 'Faster, soldiers!' },
          { lt: 'Tyliai! Klausom.', en: 'Quiet! We’re listening.' },
          { lt: 'Grįžk į postą.', en: 'Return to your post.' },
          { lt: 'Rytoj vykstame į poligoną.', en: 'Tomorrow we go to the training area.' },
        ],
        xp: 15,
      },
    ],
  },
  {
    slug: 'skaiciai',
    title: 'Skaičiai',
    description: 'Digits nought to ten — for grids, frequencies, ranges and headcounts.',
    emoji: '🔢',
    level: 'MIL1',
    color: '#16a34a',
    lessons: [
      {
        slug: 'skaitmenys',
        title: 'Skaitmenys',
        subtitle: 'Zero to five',
        emoji: '5️⃣',
        words: ['nulis', 'vienas', 'du', 'trys', 'keturi', 'penki'],
        grammar: {
          title: 'Reading numbers on the net',
          body: [
            'Grid references, frequencies and bearings are read **digit by digit**, exactly as in English radio procedure:',
            '',
            '> Azimutas **du keturi nulis** — bearing two four zero.',
            '> Kvadratas **trys aštuoni** — grid three eight.',
            '',
            'Counts of things are read normally, and here Lithuanian grammar bites: **vienas**, **du**, **keturi** change ending with the gender of what you are counting.',
            '',
            '| | masculine | feminine |',
            '| --- | --- | --- |',
            '| 1 | vienas karys | viena kuopa |',
            '| 2 | du kariai | dvi kuopos |',
            '| 4 | keturi kariai | keturios kuopos |',
            '',
            'From **five** upwards the counted noun goes into the genitive plural: *penki kariai* but *dešimt kari**ų***.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Kvadratas trys nulis penki.', en: 'Grid three zero five.' },
          { lt: 'Du priešo kariai.', en: 'Two enemy soldiers.' },
          { lt: 'Keturi kariai poste.', en: 'Four soldiers at the post.' },
        ],
        xp: 15,
      },
      {
        slug: 'skaitmenys-2',
        title: 'Skaitmenys II',
        subtitle: 'Six to ten',
        emoji: '🔟',
        words: ['šeši', 'septyni', 'aštuoni', 'devyni', 'dešimt'],
        drills: [
          { lt: 'Septyni kariai skyriuje.', en: 'Seven soldiers in the section.' },
          { lt: 'Dešimt minučių iki išvykimo.', en: 'Ten minutes until departure.' },
          { lt: 'Azimutas devyni nulis nulis.', en: 'Bearing nine zero zero.' },
        ],
        extraExercises: [
          {
            type: 'listen_type',
            prompt: 'Write the grid you hear',
            instruction: 'Type it in Lithuanian',
            audioText: 'Kvadratas aštuoni du.',
            answer: 'Kvadratas aštuoni du.',
            difficulty: 3,
          },
        ],
        xp: 15,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MIL2 — Kareivis / Soldier
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'rikiuote',
    title: 'Rikiuotė',
    description: 'Drill and ceremony: forming up, facing, marching.',
    emoji: '🥁',
    level: 'MIL2',
    color: '#38bdf8',
    lessons: [
      {
        slug: 'rikiuotis',
        title: 'Rikiuotis',
        subtitle: 'Fall in, dress, fall out',
        emoji: '👥',
        words: ['Rikiuotis!', 'Lygiuok!', 'Išsiskirstyti!', 'rikiuotė', 'eilė', 'vora', 'atstumas'],
        grammar: {
          title: 'The shape of a drill command',
          body: [
            'Every Lithuanian drill command has two parts, exactly as in English:',
            '',
            '1. **Preparatory** — who is being addressed: *Būrys…*, *Skyrius…*, *Kariai…*',
            '2. **Executive** — the shouted word itself: *…ramiai!*, *…dešinėn!*, *…marš!*',
            '',
            'The pause between them is what stops the formation moving early.',
            '',
            'Two-word marching commands split the same way: **Žengte** (preparatory manner) **marš!** (executive).',
          ].join('\n'),
        },
        drills: [
          { lt: 'Būrys, rikiuotis!', en: 'Platoon, fall in!' },
          { lt: 'Į dešinę — lygiuok!', en: 'Right — dress!' },
          { lt: 'Laisvai, išsiskirstyti!', en: 'At ease, fall out!' },
          { lt: 'Stokite į dvi eiles.', en: 'Form up in two ranks.' },
          { lt: 'Atstumas penki metrai.', en: 'Interval five metres.' },
        ],
        xp: 20,
      },
      {
        slug: 'posukiai',
        title: 'Posūkiai',
        subtitle: 'Right, left, about face',
        emoji: '🔄',
        words: ['Dešinėn!', 'Kairėn!', 'Aplink!', 'Žengte marš!', 'Bėgte marš!'],
        grammar: {
          title: 'Where “-n” comes from',
          body: [
            '**Dešinėn** and **kairėn** are frozen survivals of the *illative* case — an old Lithuanian case meaning "into". The modern equivalent is *į dešinę* ("to the right"), but drill kept the short form because it is one syllable faster to shout.',
            '',
            'So you will meet three related shapes:',
            '',
            '| Form | Use |',
            '| --- | --- |',
            '| **dešinė** | the right side (dictionary form) |',
            '| **į dešinę** | to the right (movement) |',
            '| **dešinėje** | on the right (location) |',
            '| **dešinėn!** | right face! (drill only) |',
          ].join('\n'),
        },
        drills: [
          {
            lt: 'Skyrius, dešinėn!',
            en: 'Section, right face!',
            modes: ['listen_select', 'speak'],
          },
          { lt: 'Būrys, kairėn!', en: 'Platoon, left face!', modes: ['listen_select', 'speak'] },
          { lt: 'Kariai, aplink!', en: 'Soldiers, about face!' },
          { lt: 'Būrys, žengte marš!', en: 'Platoon, forward march!' },
        ],
        extraExercises: [
          {
            type: 'react',
            prompt: 'Kairėn!',
            instruction: 'Which way do you turn?',
            audioText: 'Kairėn!',
            answer: 'Left',
            options: ['Left', 'Right', 'About — 180°', 'Stay facing forward'],
            difficulty: 2,
          },
        ],
        xp: 20,
      },
    ],
  },
  {
    slug: 'judejimas',
    title: 'Judėjimas',
    description:
      'Moving as a pair and as a section: bounding, covering, crawling, breaking contact.',
    emoji: '🏃',
    level: 'MIL2',
    color: '#0ea5e9',
    lessons: [
      {
        slug: 'judejimo-veiksmazodziai',
        title: 'Judėjimo veiksmažodžiai',
        subtitle: 'Move, run, crawl, take cover',
        emoji: '🥾',
        words: ['judėti', 'bėgti', 'šliaužti', 'slėptis', 'sustoti', 'grįžti', 'žingsnis'],
        grammar: {
          title: 'Present tense in one table',
          body: [
            'Lithuanian verbs fall into three present-tense patterns. You need the endings, not the theory — the ending alone tells the listener who is acting, which is why the pronoun is usually dropped.',
            '',
            '| | judėti (to move) | bėgti (to run) |',
            '| --- | --- | --- |',
            '| aš | jud**u** | bėg**u** |',
            '| tu | jud**i** | bėg**i** |',
            '| jis/ji | jud**a** | bėg**a** |',
            '| mes | jud**ame** | bėg**ame** |',
            '| jūs | jud**ate** | bėg**ate** |',
            '| jie/jos | jud**a** | bėg**a** |',
            '',
            '**Judu!** on its own therefore means "I am moving!" — the call you make when you break cover.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Judu! Dengk!', en: 'Moving! Cover me!' },
          { lt: 'Bėk prie priedangos!', en: 'Run to cover!' },
          { lt: 'Šliaužk iki griovio.', en: 'Crawl to the ditch.' },
          { lt: 'Slėpkitės! Minosvaidžiai!', en: 'Take cover! Mortars!' },
          { lt: 'Sustojame prie miško.', en: 'We halt at the treeline.' },
        ],
        xp: 20,
      },
      {
        slug: 'poroje',
        title: 'Poroje',
        subtitle: 'Buddy pairs: I move, you cover',
        emoji: '👬',
        words: ['dengti', 'trauktis', 'pulti', 'laukti'],
        grammar: {
          title: 'The two-word exchange that keeps you alive',
          body: [
            'Bounding in pairs runs on a fixed call and response. Both halves are one word:',
            '',
            '> — **Judu!** *(Moving!)*',
            '> — **Dengiu!** *(Covering!)*',
            '',
            'Then reverse. Add a direction or distance if there is time: *Judu dešinėn, dešimt metrų!*',
            '',
            'The imperative forms you will hear shouted at you: **Dengk!** (cover — to one), **Dengkite!** (to several), **Judėk!** (move).',
          ].join('\n'),
        },
        drills: [
          { lt: 'Dengiu! Judėk!', en: 'Covering! Move!' },
          { lt: 'Skyrius, trauktis!', en: 'Section, withdraw!' },
          { lt: 'Puolame iš dešinės.', en: 'We attack from the right.' },
          { lt: 'Laukite mano signalo.', en: 'Wait for my signal.' },
        ],
        xp: 20,
      },
    ],
  },
  {
    slug: 'kryptys',
    title: 'Kryptys',
    description: 'Saying where something is — relative to you, and on the compass.',
    emoji: '🧭',
    level: 'MIL2',
    color: '#0284c7',
    lessons: [
      {
        slug: 'santykines-kryptys',
        title: 'Santykinės kryptys',
        subtitle: 'Left, right, ahead, behind',
        emoji: '↔️',
        words: ['kairė', 'dešinė', 'tiesiai', 'atgal', 'priekyje', 'už', 'šone'],
        grammar: {
          title: 'Three forms of every direction',
          body: [
            'Lithuanian marks the difference between *being* somewhere and *moving* there with the case ending, not with a different preposition. Learn all three at once:',
            '',
            '| Meaning | Form | Example |',
            '| --- | --- | --- |',
            '| the side itself | **dešinė** | *Kur dešinė?* |',
            '| motion towards | **į dešinę** | *Judame į dešinę.* |',
            '| location at | **dešinėje** | *Priešas dešinėje.* |',
            '',
            'A contact report uses the **location** form: *Kontaktas — dešinėje!*',
            'A movement order uses the **motion** form: *Judam į dešinę!*',
          ].join('\n'),
        },
        drills: [
          { lt: 'Priešas kairėje!', en: 'Enemy on the left!' },
          { lt: 'Judame į dešinę.', en: 'We are moving to the right.' },
          { lt: 'Priekyje pastatas.', en: 'A building ahead.' },
          { lt: 'Priešas už tilto.', en: 'The enemy is beyond the bridge.' },
          { lt: 'Judėjimas dešiniame šone.', en: 'Movement on the right flank.' },
        ],
        xp: 20,
      },
      {
        slug: 'pasaulio-salys',
        title: 'Pasaulio šalys',
        subtitle: 'North, south, east, west',
        emoji: '🗺️',
        words: ['šiaurė', 'pietūs', 'rytai', 'vakarai', 'šiaurės rytai', 'pietryčiai', 'kryptis'],
        grammar: {
          title: 'Three of the four are plural',
          body: [
            'Only **šiaurė** (north) is singular. *Pietūs*, *rytai* and *vakarai* are grammatically plural, which changes every ending that follows them:',
            '',
            '- *į šiaurę* — northwards · *šiaurėje* — in the north',
            '- *į pietus* — southwards · *pietuose* — in the south',
            '- *į rytus* — eastwards · *rytuose* — in the east',
            '- *į vakarus* — westwards · *vakaruose* — in the west',
            '',
            'They double as everyday words: **pietūs** is also lunch, **rytai** is related to *rytas* (morning, where the sun rises), **vakarai** to *vakaras* (evening).',
            '',
            'Intercardinals: **šiaurės rytai** (NE) and **šiaurės vakarai** (NW) are two words; **pietryčiai** (SE) and **pietvakariai** (SW) are one.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Priešas į šiaurę nuo kelio.', en: 'Enemy north of the road.' },
          { lt: 'Judame į pietus.', en: 'We are moving south.' },
          { lt: 'Judėjimas iš šiaurės rytų.', en: 'Movement from the north-east.' },
          { lt: 'Judėjimo kryptis — šiaurė.', en: 'Direction of movement — north.' },
        ],
        xp: 20,
      },
      {
        slug: 'prielinksniai',
        title: 'Prielinksniai',
        subtitle: 'Between, near, under, across',
        emoji: '🔗',
        words: ['tarp', 'prie', 'po', 'per', 'aplink'],
        grammar: {
          title: 'Every preposition rules a case',
          body: [
            'A Lithuanian preposition forces the noun after it into a particular case. Learn the preposition and its case as a single unit — the wrong ending is as wrong as the wrong word.',
            '',
            '| Preposition | Case | Example |',
            '| --- | --- | --- |',
            '| **tarp** (between) | genitive | tarp med**žių** |',
            '| **prie** (at, by) | genitive | prie kel**io** |',
            '| **už** (behind) | genitive | už tilt**o** |',
            '| **aplink** (around) | accusative | aplink pastat**ą** |',
            '| **per** (across) | accusative | per up**ę** |',
            '| **po** (under) | instrumental | po tilt**u** |',
          ].join('\n'),
        },
        drills: [
          { lt: 'Priešas tarp namų.', en: 'The enemy is among the houses.' },
          { lt: 'Susitinkame prie tilto.', en: 'We meet at the bridge.' },
          { lt: 'Priedanga po tiltu.', en: 'Cover under the bridge.', blank: 'tiltu' },
          { lt: 'Judame per lauką.', en: 'We move across the field.', blank: 'lauką' },
          { lt: 'Einame aplink mišką.', en: 'We are going around the wood.' },
        ],
        xp: 25,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MIL3 — Skyrininkas / Section Member
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'vietove',
    title: 'Vietovė',
    description: 'Describing Lithuanian ground: forest, marsh, ditch, treeline.',
    emoji: '🌲',
    level: 'MIL3',
    color: '#a3e635',
    lessons: [
      {
        slug: 'gamtine-vietove',
        title: 'Gamtinė vietovė',
        subtitle: 'Forest, field, marsh, water',
        emoji: '🏞️',
        words: ['miškas', 'laukas', 'pelkė', 'upė', 'ežeras', 'kalva', 'slėnis', 'griovys'],
        grammar: {
          title: 'The locative — “in the forest”',
          body: [
            'Lithuanian has no word for "in" before a place. The **locative** ending carries the meaning by itself:',
            '',
            '| Dictionary form | "in / at" |',
            '| --- | --- |',
            '| miškas | mišk**e** |',
            '| laukas | lauk**e** |',
            '| kaimas | kaim**e** |',
            '| pelkė | pelk**ėje** |',
            '| upė | up**ėje** |',
            '| kalva | kalv**oje** |',
            '',
            'So *Priešas miške* is a complete sentence: "The enemy is in the woods." No preposition, no verb.',
            '',
            'Useful accident: **lauke** means both "in the field" and simply "outside".',
          ].join('\n'),
        },
        drills: [
          { lt: 'Priešas miške.', en: 'Enemy in the woods.' },
          { lt: 'Atviras laukas — nėra priedangos.', en: 'Open field — no cover.' },
          { lt: 'Kelias uždarytas — pelkė.', en: 'Route closed — marsh.' },
          { lt: 'Pozicija ant kalvos.', en: 'Position on the hill.' },
          { lt: 'Priedanga griovyje!', en: 'Cover in the ditch!', blank: 'griovyje' },
        ],
        xp: 25,
      },
      {
        slug: 'zmogaus-vietove',
        title: 'Žmogaus sukurta vietovė',
        subtitle: 'Roads, bridges, buildings, villages',
        emoji: '🏘️',
        words: [
          'kelias',
          'takas',
          'tiltas',
          'geležinkelis',
          'pastatas',
          'kaimas',
          'priedanga',
          'kliūtis',
          'praeinamas',
        ],
        drills: [
          { lt: 'Kelias užminuotas.', en: 'The road is mined.' },
          { lt: 'Tiltas sunaikintas.', en: 'The bridge is destroyed.' },
          { lt: 'Dviaukštis pastatas kairėje.', en: 'A two-storey building on the left.' },
          { lt: 'Kelias praeinamas transportui.', en: 'The route is passable for vehicles.' },
          { lt: 'Kliūtis kelyje — medžiai.', en: 'Obstacle on the route — trees.' },
        ],
        xp: 25,
      },
    ],
  },
  {
    slug: 'zemelapis',
    title: 'Žemėlapis',
    description: 'Map and compass: grids, bearings, contours, rally points.',
    emoji: '🗺️',
    level: 'MIL3',
    color: '#84cc16',
    lessons: [
      {
        slug: 'zemelapio-skaitymas',
        title: 'Žemėlapio skaitymas',
        subtitle: 'Grid, scale, contours, elevation',
        emoji: '📐',
        words: ['žemėlapis', 'koordinatės', 'kvadratas', 'mastelis', 'horizontalės', 'aukštis'],
        grammar: {
          title: 'Reading a grid aloud',
          body: [
            'A Lithuanian grid reference is spoken digit by digit, with the word **kvadratas** (grid square) in front:',
            '',
            '> **Kvadratas keturi du, penki vienas.**',
            '> *Grid four two, five one.*',
            '',
            'Height is given in metres with **aukštis**: *Aukštis šimtas keturiasdešimt metrų.*',
            '',
            'Note what "close contours" means when you say it: *Tankios horizontalės — status šlaitas* — dense contour lines, a steep slope.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Pažymėk poziciją žemėlapyje.', en: 'Mark the position on the map.' },
          { lt: 'Priešas kvadrate keturi du.', en: 'Enemy in grid square four two.' },
          { lt: 'Tankios horizontalės — status šlaitas.', en: 'Close contours — a steep slope.' },
          {
            lt: 'Aukštis šimtas keturiasdešimt metrų.',
            en: 'Elevation one hundred and forty metres.',
          },
        ],
        xp: 25,
      },
      {
        slug: 'orientavimasis',
        title: 'Orientavimasis',
        subtitle: 'Compass, bearing, route, rally point',
        emoji: '🧭',
        words: [
          'kompasas',
          'azimutas',
          'orientyras',
          'maršrutas',
          'susitikimo taškas',
          'orientuotis',
          'pažymėti',
          'nustatyti',
        ],
        drills: [
          { lt: 'Azimutas trys šeši nulis.', en: 'Bearing three six zero.' },
          { lt: 'Orientyras — vienišas medis.', en: 'Reference point — the lone tree.' },
          { lt: 'Susitikimo taškas prie tilto.', en: 'Rally point at the bridge.' },
          { lt: 'Nustatykite savo koordinates.', en: 'Determine your coordinates.' },
          { lt: 'Orientuojuosi pagal kompasą.', en: 'I am orienting myself by compass.' },
        ],
        xp: 25,
      },
      {
        slug: 'laikas-atstumas',
        title: 'Laikas ir atstumas',
        subtitle: 'Hours, minutes, metres, kilometres',
        emoji: '⏱️',
        words: [
          'laikas',
          'valanda',
          'minutė',
          'para',
          'naktis',
          'prieš',
          'iki',
          'metras',
          'kilometras',
        ],
        grammar: {
          title: 'Military time and the word “para”',
          body: [
            'Times are read digit by digit: **08:00 → nulis aštuoni nulis nulis**. In ordinary speech you would say *aštuntą valandą* ("at the eighth hour").',
            '',
            'Lithuanian has a word English lacks: **para** — a full 24-hour period, day *and* night. *Užduotis truks parą* means the task runs a full day and night, which *diena* would not convey.',
            '',
            'Two prepositions of time, two cases:',
            '- **prieš** + accusative — *prieš aušr**ą*** (before dawn)',
            '- **iki** + genitive — *iki vidurnakč**io*** (until midnight)',
          ].join('\n'),
        },
        drills: [
          { lt: 'Išvykstame aštuntą valandą.', en: 'We depart at eight o’clock.' },
          { lt: 'Pozicijas užimame prieš aušrą.', en: 'We occupy positions before dawn.' },
          { lt: 'Laikome poziciją iki vidurnakčio.', en: 'We hold the position until midnight.' },
          { lt: 'Taikinys už trijų šimtų metrų.', en: 'Target at three hundred metres.' },
          { lt: 'Judėsime naktį.', en: 'We will move at night.' },
        ],
        xp: 25,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MIL4 — Specialistas / Specialist
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'ginkluote',
    title: 'Ginkluotė',
    description: 'Weapons, ammunition, and the commands that go with them.',
    emoji: '🎯',
    level: 'MIL4',
    color: '#fb923c',
    lessons: [
      {
        slug: 'ginklai',
        title: 'Ginklai',
        subtitle: 'Rifle, machine gun, mortar, grenade',
        emoji: '🔫',
        words: [
          'ginklas',
          'šautuvas',
          'kulkosvaidis',
          'minosvaidis',
          'granata',
          'šoviniai',
          'apkaba',
          'saugiklis',
        ],
        grammar: {
          title: 'Lithuanian builds words out of parts',
          body: [
            'Much military vocabulary is transparent once you can see the seams — you can often guess a new word:',
            '',
            '| Word | Built from | Literally |',
            '| --- | --- | --- |',
            '| **šautuvas** | šauti (shoot) | shooter |',
            '| **kulkosvaidis** | kulka + svaidyti | bullet-hurler |',
            '| **minosvaidis** | mina + svaidyti | mine-hurler |',
            '| **geležinkelis** | geležis + kelias | iron road |',
            '| **sraigtasparnis** | sraigtas + sparnas | screw-wing |',
            '| **visureigis** | visur + eiti | goes-everywhere |',
            '',
            'When you meet an unknown compound, split it and the meaning usually falls out.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Patikrinkite ginklus.', en: 'Check weapons.' },
          { lt: 'Šautuvas užtaisytas.', en: 'The rifle is loaded.' },
          { lt: 'Baigiasi šoviniai!', en: 'Running out of ammo!' },
          { lt: 'Užstatykite saugiklį.', en: 'Put the safety on.' },
        ],
        xp: 25,
      },
      {
        slug: 'ugnies-komandos',
        title: 'Ugnies komandos',
        subtitle: 'Fire, cease fire, load, target',
        emoji: '🔥',
        words: ['taikinys', 'šauti', 'Ugnis!', 'Nutraukti ugnį!', 'Užtaisyk!', 'mina', 'sprogmuo'],
        grammar: {
          title: 'A fire command in Lithuanian',
          body: [
            'The order of information matches NATO practice — direction, description, range, then the executive word:',
            '',
            '> **Taikinys — dešinėje, priešo kulkosvaidis, du šimtai — ugnis!**',
            '> *Target — right, enemy machine gun, two hundred — fire!*',
            '',
            'Prohibitions use a negated **infinitive**, which is blunter and clearer than an imperative: **Nešaudyti!** (do not fire), **Nejudėti!** (do not move), **Nutraukti ugnį!** (cease fire).',
            '',
            'One false friend to bury now: English *"repeat"* is a fire-support term. If you want a message resent, Lithuanian **Pakartokite!** is unambiguous and carries no such risk.',
          ].join('\n'),
        },
        drills: [
          {
            lt: 'Taikinys — dešinėje, du šimtai metrų.',
            en: 'Target — right, two hundred metres.',
          },
          { lt: 'Skyrius — ugnis!', en: 'Section — fire!' },
          { lt: 'Nutraukti ugnį! Saviškiai priekyje!', en: 'Cease fire! Friendlies to the front!' },
          { lt: 'Nešaudyti be įsakymo!', en: 'Do not fire without an order!' },
          { lt: 'Dėmesio — minos!', en: 'Warning — mines!' },
        ],
        extraExercises: [
          {
            type: 'react',
            prompt: 'Nutraukti ugnį!',
            instruction: 'What do you do?',
            audioText: 'Nutraukti ugnį!',
            answer: 'Stop firing immediately',
            options: [
              'Stop firing immediately',
              'Open fire',
              'Reload and continue',
              'Fire one more round',
            ],
            difficulty: 2,
          },
        ],
        xp: 30,
      },
    ],
  },
  {
    slug: 'ekipuote',
    title: 'Ekipuotė',
    description: 'What you carry: protection, load, optics, field kit.',
    emoji: '🎒',
    level: 'MIL4',
    color: '#f97316',
    lessons: [
      {
        slug: 'asmenine-ekipuote',
        title: 'Asmeninė ekipuotė',
        subtitle: 'Helmet, armour, rucksack, boots',
        emoji: '⛑️',
        words: ['uniforma', 'šalmas', 'neperšaunama liemenė', 'kuprinė', 'batai', 'dujokaukė'],
        drills: [
          { lt: 'Užsidėkite šalmus.', en: 'Put on your helmets.' },
          {
            lt: 'Be neperšaunamos liemenės neišeiname.',
            en: 'We don’t go out without body armour.',
          },
          { lt: 'Kuprinė per sunki.', en: 'The rucksack is too heavy.' },
          { lt: 'Dujos! Užsidėkite dujokaukes!', en: 'Gas! Put on gas masks!' },
        ],
        xp: 25,
      },
      {
        slug: 'lauko-ekipuote',
        title: 'Lauko ekipuotė',
        subtitle: 'Optics, digging, sleeping, light',
        emoji: '🔦',
        words: [
          'žiūronai',
          'naktinio matymo prietaisas',
          'kastuvėlis',
          'gertuvė',
          'miegmaišis',
          'palapinė',
          'žibintuvėlis',
          'virvė',
        ],
        drills: [
          { lt: 'Stebiu per žiūronus.', en: 'I am observing through binoculars.' },
          { lt: 'Įjunkite naktinio matymo prietaisus.', en: 'Switch on night-vision devices.' },
          { lt: 'Kask apkasą kastuvėliu.', en: 'Dig the trench with the entrenching tool.' },
          { lt: 'Pripildykite gertuves.', en: 'Fill your canteens.' },
          { lt: 'Naudokite raudoną žibintuvėlio šviesą.', en: 'Use the red torch light.' },
        ],
        xp: 25,
      },
      {
        slug: 'technika',
        title: 'Technika ir aprūpinimas',
        subtitle: 'Vehicles, fuel, rations, resupply',
        emoji: '🚚',
        words: [
          'transporto priemonė',
          'sunkvežimis',
          'visureigis',
          'šarvuotis',
          'sraigtasparnis',
          'bepilotis orlaivis',
          'degalai',
          'atsargos',
          'sausas davinys',
          'aprūpinimas',
        ],
        drills: [
          { lt: 'Trys transporto priemonės kelyje.', en: 'Three vehicles on the road.' },
          {
            lt: 'Priešo šarvuotis kvadrate penki du.',
            en: 'Enemy armoured vehicle in grid five two.',
          },
          { lt: 'Virš mūsų bepilotis orlaivis.', en: 'There is a drone above us.' },
          { lt: 'Baigiasi degalai.', en: 'We are running out of fuel.' },
          { lt: 'Aprūpinimas atvyks rytą.', en: 'Resupply will arrive in the morning.' },
        ],
        xp: 30,
      },
    ],
  },
  {
    slug: 'laipsniai',
    title: 'Laipsniai ir struktūra',
    description: 'Who outranks whom, and what a Lithuanian unit is called.',
    emoji: '🎖️',
    level: 'MIL4',
    color: '#ea580c',
    lessons: [
      {
        slug: 'kariniai-laipsniai',
        title: 'Kariniai laipsniai',
        subtitle: 'Private to colonel',
        emoji: '⭐',
        words: [
          'laipsnis',
          'eilinis',
          'grandinis',
          'puskarininkis',
          'viršila',
          'leitenantas',
          'kapitonas',
          'majoras',
          'pulkininkas',
        ],
        grammar: {
          title: 'The Lithuanian NCO ladder is not “sergeant”',
          body: [
            'Lithuania does not use the Western *sergeant* family. The whole NCO ladder is built on **puskarininkis** — literally "half-officer":',
            '',
            '| Lithuanian | Rough equivalent |',
            '| --- | --- |',
            '| eilinis | private |',
            '| vyresnysis eilinis | senior private |',
            '| grandinis | corporal |',
            '| jaunesnysis puskarininkis | junior sergeant |',
            '| **puskarininkis** | sergeant |',
            '| vyresnysis puskarininkis | senior sergeant |',
            '| viršila | sergeant major |',
            '',
            '**Vyresnysis** ("senior") and **jaunesnysis** ("junior") modify a rank the way they do in English.',
            '',
            'Officers are more familiar: *leitenantas, vyresnysis leitenantas, kapitonas, majoras, pulkininkas leitenantas, pulkininkas*, then the generals.',
            '',
            'Remember the vocative when you address any of them: *pone kapitone*, *pone puskarininki*.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Koks jūsų laipsnis?', en: 'What is your rank?' },
          { lt: 'Taip, pone puskarininki!', en: 'Yes, sergeant!' },
          { lt: 'Leiskite kreiptis, pone leitenante!', en: 'Permission to speak, lieutenant!' },
          { lt: 'Kapitonas vadovauja kuopai.', en: 'The captain commands the company.' },
        ],
        xp: 30,
      },
      {
        slug: 'daliniai',
        title: 'Daliniai',
        subtitle: 'Section, platoon, company, battalion',
        emoji: '🏛️',
        words: ['skyrius', 'būrys', 'kuopa', 'batalionas', 'brigada', 'štabas'],
        drills: [
          { lt: 'Skyrius pasiruošęs.', en: 'The section is ready.' },
          { lt: 'Būrio vadas — leitenantas.', en: 'The platoon commander is a lieutenant.' },
          {
            lt: 'Batalioną sudaro kelios kuopos.',
            en: 'A battalion is made up of several companies.',
          },
          { lt: 'Pranešimas siunčiamas į štabą.', en: 'The report is being sent to headquarters.' },
        ],
        xp: 25,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MIL5 — Ryšininkas / Signaller
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'radijo-rysys',
    title: 'Radijo ryšys',
    description: 'Opening a net, acknowledging, asking again, closing down.',
    emoji: '📡',
    level: 'MIL5',
    color: '#c084fc',
    lessons: [
      {
        slug: 'stotis',
        title: 'Stotis',
        subtitle: 'Radio, call sign, frequency, check',
        emoji: '📻',
        words: [
          'radijo stotis',
          'ryšys',
          'šaukinys',
          'dažnis',
          'ryšio patikra',
          'Kaip girdite?',
          'Girdžiu gerai',
        ],
        grammar: {
          title: 'A radio check, start to finish',
          body: [
            'The exchange is short and fixed. Learn it as a script:',
            '',
            '> **— Vilkas vienas, čia Erelis. Ryšio patikra. Kaip girdite?**',
            '> *Wolf One, this is Eagle. Radio check. How do you read me?*',
            '>',
            '> **— Erelis, čia Vilkas vienas. Girdžiu gerai. Baigiu.**',
            '> *Eagle, this is Wolf One. Read you clearly. Out.*',
            '',
            '**Čia** means "this is" — literally "here". Called station first, then your own call sign.',
            '',
            'If reception is poor: **Girdžiu prastai** or **Prastas ryšys, pakartokite.**',
          ].join('\n'),
        },
        drills: [
          { lt: 'Vilkas vienas, ryšio patikra.', en: 'Wolf One, radio check.' },
          { lt: 'Kaip girdite?', en: 'How do you read me?', modes: ['listen_type', 'speak'] },
          { lt: 'Girdžiu gerai, perduokite.', en: 'Read you clearly, send.' },
          { lt: 'Prastas ryšys, pakartokite.', en: 'Poor comms, say again.' },
          {
            lt: 'Pereiname į atsarginį dažnį.',
            en: 'We are switching to the alternate frequency.',
          },
        ],
        xp: 30,
      },
      {
        slug: 'tarnybiniai-zodziai',
        title: 'Tarnybiniai žodžiai',
        subtitle: 'Roger, standby, affirmative, out',
        emoji: '🔊',
        words: [
          'Priėmiau',
          'Perduodu',
          'Laukite',
          'Patvirtinkite',
          'Teigiamai',
          'Neigiamai',
          'Baigiu',
          'Skubiai',
        ],
        grammar: {
          title: 'Why not just say “taip”?',
          body: [
            'On a degraded net, *taip* (yes) and *ne* (no) are one syllable each and easily lost or misheard as each other. Prowords are chosen to be long and phonetically distinct:',
            '',
            '| Instead of | Say | Meaning |',
            '| --- | --- | --- |',
            '| taip | **Teigiamai** | affirmative |',
            '| ne | **Neigiamai** | negative |',
            '| gerai | **Priėmiau** | received / roger |',
            '| — | **Supratau** | understood |',
            '| — | **Vykdau** | wilco |',
            '| — | **Laukite** | standby |',
            '| — | **Baigiu** | out |',
            '',
            'Note the pair that English collapses: **Priėmiau** acknowledges receipt; **Vykdau** promises action. Send both if both are true.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Priėmiau, baigiu.', en: 'Roger, out.' },
          { lt: 'Perduodu koordinates.', en: 'Passing coordinates.' },
          { lt: 'Laukite, tikrinu.', en: 'Standby, checking.' },
          { lt: 'Teigiamai, pozicija užimta.', en: 'Affirmative, position occupied.' },
          { lt: 'Neigiamai, priešo nematau.', en: 'Negative, I do not see the enemy.' },
        ],
        extraExercises: [
          {
            type: 'select',
            prompt: 'You have understood the order and you are acting on it. What do you send?',
            answer: 'Supratau, vykdau.',
            options: ['Supratau, vykdau.', 'Priėmiau, laukite.', 'Neigiamai.', 'Kaip girdite?'],
            explanation:
              '“Supratau” = understood, “vykdau” = carrying it out. “Priėmiau” alone only confirms receipt.',
            difficulty: 3,
          },
        ],
        xp: 30,
      },
    ],
  },
  {
    slug: 'pranesimai',
    title: 'Pranešimai',
    description: 'Structured reporting: what you saw, how many, where, doing what.',
    emoji: '📨',
    level: 'MIL5',
    color: '#a855f7',
    lessons: [
      {
        slug: 'ka-maciau',
        title: 'Ką mačiau',
        subtitle: 'Observing and spotting',
        emoji: '👁️',
        words: ['stebėti', 'pastebėjau', 'pranešti', 'pranešimas', 'padėtis'],
        drills: [
          { lt: 'Pastebėjau judėjimą miške.', en: 'I have spotted movement in the woods.' },
          { lt: 'Stebiu kelią iš pozicijos.', en: 'I am observing the road from the position.' },
          { lt: 'Pranešu apie priešo judėjimą.', en: 'I am reporting enemy movement.' },
          { lt: 'Padėtis kontroliuojama.', en: 'The situation is under control.' },
        ],
        xp: 30,
      },
      {
        slug: 'kontakto-pranesimas',
        title: 'Kontakto pranešimas',
        subtitle: 'Size, location, activity',
        emoji: '📊',
        words: ['priešas', 'saviškiai', 'civiliai', 'kiekis', 'vieta', 'veiksmas'],
        grammar: {
          title: 'The four lines of a contact report',
          body: [
            'Lithuanian reporting follows the same skeleton as a NATO SALUTE report. Four lines, always in this order:',
            '',
            '| Line | Lithuanian | Example |',
            '| --- | --- | --- |',
            '| Size | **Kiekis** | *Kiekis — apie dešimt karių.* |',
            '| Location | **Vieta** | *Vieta — kvadratas trys aštuoni.* |',
            '| Activity | **Veiksmas** | *Veiksmas — juda į vakarus.* |',
            '| Time | **Laikas** | *Laikas — nulis devyni trys nulis.* |',
            '',
            'Full example, spoken as one block:',
            '',
            '> **Čia Vilkas vienas. Priešas. Kiekis — apie dešimt. Vieta — kvadratas trys aštuoni. Veiksmas — juda į vakarus. Baigiu.**',
            '',
            'The word **apie** ("about, approximately") is doing a lot of work — use it rather than inventing precision you do not have.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Kiekis — apie dešimt karių.', en: 'Size — about ten soldiers.' },
          { lt: 'Vieta — kvadratas trys aštuoni.', en: 'Location — grid three eight.' },
          { lt: 'Veiksmas — juda į vakarus.', en: 'Activity — moving west.' },
          { lt: 'Saviškiai dešinėje, nešaudyti!', en: 'Friendlies on the right, do not fire!' },
          { lt: 'Kaime yra civilių.', en: 'There are civilians in the village.' },
        ],
        xp: 35,
      },
      {
        slug: 'prasymai',
        title: 'Prašymai',
        subtitle: 'Requesting support, permission, resupply',
        emoji: '🙏',
        words: ['parama', 'pastiprinimas', 'prašau', 'leidimas', 'reikia'],
        grammar: {
          title: 'What you ask for goes in the genitive',
          body: [
            'Two verbs of asking, both followed by the **genitive**, not the accusative:',
            '',
            '- **prašau** + genitive — *prašau param**os***, *prašau leidim**o***',
            '- **reikia** + genitive — *reikia vand**ens***, *reikia šovin**ių***',
            '',
            '**Reikia** is impersonal and puts the person who needs into the **dative**:',
            '',
            '> **Mums reikia vandens.** — *We need water.* (literally: "to us there is need of water")',
            '> **Man reikia mediko.** — *I need a medic.*',
            '',
            'This dative-subject pattern shows up again with *skauda* (it hurts) and *patinka* (is pleasing). Lithuanian often makes the person the recipient rather than the actor.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Prašau ugnies paramos.', en: 'I request fire support.' },
          { lt: 'Prašau leidimo judėti.', en: 'I request permission to move.' },
          { lt: 'Reikia pastiprinimo.', en: 'Reinforcement is needed.' },
          { lt: 'Mums reikia vandens ir šovinių.', en: 'We need water and ammunition.' },
          { lt: 'Leidimas suteiktas.', en: 'Permission granted.' },
        ],
        xp: 35,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MIL6 — Vadas / Commander
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: 'kontaktas',
    title: 'Kontaktas',
    description: 'Contact drills: the words shouted in the first ten seconds.',
    emoji: '💥',
    level: 'MIL6',
    color: '#f87171',
    lessons: [
      {
        slug: 'kontakto-sauksmai',
        title: 'Kontakto šauksmai',
        subtitle: 'Contact, cover, reloading, clear',
        emoji: '📢',
        words: ['Kontaktas!', 'Į priedangą!', 'Perkraunu!', 'Švaru!', 'snaiperis', 'pavojus'],
        grammar: {
          title: 'One word, then the detail',
          body: [
            'Under fire, the first word carries the warning and the rest fills it in. Never bury the alarm inside a sentence.',
            '',
            '> **Kontaktas — dešinėje, du šimtai!**',
            '> *Contact — right, two hundred!*',
            '',
            'The words that stand alone as a complete warning: **Kontaktas!**, **Snaiperis!**, **Granata!**, **Minos!**, **Dujos!**, **Medikas!**',
            '',
            'Each is a noun used as an interjection. There is no verb and none is needed.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Kontaktas — priekyje, šimtas metrų!', en: 'Contact — front, one hundred metres!' },
          { lt: 'Į priedangą! Minosvaidžiai!', en: 'Take cover! Mortars!' },
          { lt: 'Perkraunu! Dengk!', en: 'Reloading! Cover me!' },
          { lt: 'Kambarys švaru!', en: 'Room clear!' },
          { lt: 'Snaiperis! Visi gulk!', en: 'Sniper! Everyone down!' },
        ],
        extraExercises: [
          {
            type: 'react',
            prompt: 'Į priedangą!',
            instruction: 'What do you do?',
            audioText: 'Į priedangą!',
            answer: 'Get behind cover immediately',
            options: [
              'Get behind cover immediately',
              'Advance towards the enemy',
              'Stand up and observe',
              'Reload your weapon',
            ],
            difficulty: 2,
          },
          {
            type: 'react',
            prompt: 'Perkraunu!',
            instruction: 'Your partner shouts this. What does it mean for you?',
            audioText: 'Perkraunu!',
            answer: 'They are reloading — cover their arc',
            options: [
              'They are reloading — cover their arc',
              'They are moving forward',
              'They are hit',
              'They see the enemy',
            ],
            difficulty: 3,
          },
        ],
        xp: 35,
      },
      {
        slug: 'valdymas-ugnyje',
        title: 'Valdymas ugnyje',
        subtitle: 'Do not fire, fall back, hold',
        emoji: '🛑',
        words: ['Nešaudyti!', 'Pasitrauk!', 'Laikyti poziciją!'],
        grammar: {
          title: 'Orders as bare infinitives',
          body: [
            'For orders to a whole group under stress, Lithuanian often uses the **plain infinitive** rather than an imperative. It is shorter, it is impersonal, and it does not force you to pick singular or plural in the moment:',
            '',
            '| Infinitive order | Meaning |',
            '| --- | --- |',
            '| **Nešaudyti!** | Do not fire! |',
            '| **Nutraukti ugnį!** | Cease fire! |',
            '| **Laikyti poziciją!** | Hold the position! |',
            '| **Nejudėti!** | Do not move! |',
            '| **Trauktis!** | Withdraw! |',
            '',
            'Compare with the imperative, which is aimed at a person: **Pasitrauk!** (you, fall back) / **Pasitraukite!** (all of you, fall back).',
          ].join('\n'),
        },
        drills: [
          { lt: 'Nešaudyti! Civiliai!', en: 'Do not fire! Civilians!' },
          { lt: 'Pasitraukite prie griovio!', en: 'Fall back to the ditch!' },
          { lt: 'Laikyti poziciją iki paramos!', en: 'Hold the position until support arrives!' },
        ],
        xp: 30,
      },
    ],
  },
  {
    slug: 'medicina',
    title: 'Medicinos pagalba',
    description: 'Casualty care and evacuation — the vocabulary you hope not to use.',
    emoji: '⚕️',
    level: 'MIL6',
    color: '#ef4444',
    lessons: [
      {
        slug: 'sauksmas-medikui',
        title: 'Šauksmas medikui',
        subtitle: 'Medic, wounded, bleeding',
        emoji: '🆘',
        words: ['Medikas!', 'sužeistas', 'žaizda', 'kraujavimas', 'Gelbėkite!'],
        grammar: {
          title: 'Reporting a casualty’s state',
          body: [
            'Three states, three phrases. Give them in this order — the medic triages on them:',
            '',
            '| State | Lithuanian |',
            '| --- | --- |',
            '| conscious | **sąmoningas** |',
            '| unconscious | **be sąmonės** |',
            '| breathing | **kvėpuoja** |',
            '| not breathing | **nekvėpuoja** |',
            '| severe bleeding | **stiprus kraujavimas** |',
            '',
            'A complete casualty call:',
            '',
            '> **Medikas! Vienas sužeistas, sąmoningas, stiprus kraujavimas, kairė koja.**',
            '> *Medic! One casualty, conscious, severe bleeding, left leg.*',
            '',
            '**Sužeistas** is a participle and agrees: *sužeistas* (male), *sužeista* (female), *sužeisti* (several).',
          ].join('\n'),
        },
        drills: [
          { lt: 'Medikas! Sužeistas!', en: 'Medic! Man down!' },
          { lt: 'Vienas sužeistas, sąmoningas.', en: 'One casualty, conscious.' },
          { lt: 'Stiprus kraujavimas!', en: 'Severe bleeding!' },
          { lt: 'Žaizda kairėje kojoje.', en: 'A wound to the left leg.' },
        ],
        xp: 35,
      },
      {
        slug: 'pirmoji-pagalba',
        title: 'Pirmoji pagalba',
        subtitle: 'Tourniquet, dressing, breathing, consciousness',
        emoji: '🩹',
        words: ['turniketas', 'tvarstis', 'pirmoji pagalba', 'kvėpuoja', 'be sąmonės', 'Laikykis!'],
        drills: [
          { lt: 'Uždėk turniketą virš žaizdos.', en: 'Apply a tourniquet above the wound.' },
          { lt: 'Reikia švaraus tvarsčio.', en: 'A clean dressing is needed.' },
          { lt: 'Kvėpuoja, bet be sąmonės.', en: 'Breathing, but unconscious.' },
          { lt: 'Laikykis, medikas jau eina.', en: 'Hang in there, the medic is coming.' },
        ],
        xp: 35,
      },
      {
        slug: 'evakuacija',
        title: 'Evakuacija',
        subtitle: 'Stretcher, evacuation, urgent request',
        emoji: '🚁',
        words: ['neštuvai', 'evakuacija'],
        grammar: {
          title: 'Requesting an evacuation',
          body: [
            'Keep it to four facts, in order — location, number, state, landing point:',
            '',
            '> **Prašau skubios evakuacijos. Vieta — kvadratas keturi vienas. Vienas sužeistas, sąmoningas. Nusileidimo vieta pažymėta dūmais.**',
            '',
            '> *I request urgent evacuation. Location — grid four one. One casualty, conscious. Landing point marked with smoke.*',
            '',
            'Note **skubios evakuacijos** — both words in the genitive, because *prašau* governs the genitive.',
          ].join('\n'),
        },
        drills: [
          { lt: 'Atneškite neštuvus!', en: 'Bring a stretcher!' },
          { lt: 'Prašau skubios evakuacijos.', en: 'I request urgent evacuation.' },
          {
            lt: 'Sraigtasparnis nusileis už dešimt minučių.',
            en: 'The helicopter will land in ten minutes.',
          },
        ],
        xp: 35,
      },
    ],
  },
  {
    slug: 'isakymai',
    title: 'Įsakymai ir komanda',
    description: 'Giving a short set of orders and confirming they were understood.',
    emoji: '📋',
    level: 'MIL6',
    color: '#dc2626',
    lessons: [
      {
        slug: 'uzduotis',
        title: 'Užduotis',
        subtitle: 'Mission, objective, plan, signal',
        emoji: '🎯',
        words: ['užduotis', 'tikslas', 'planas', 'signalas', 'įsakyti', 'vykdyti'],
        grammar: {
          title: 'A five-line order',
          body: [
            'A short Lithuanian orders group covers the same ground as a five-paragraph order, compressed:',
            '',
            '1. **Padėtis** — *Priešas kvadrate keturi du, apie dešimt karių.*',
            '2. **Užduotis** — *Mūsų užduotis — stebėti kelią.*',
            '3. **Vykdymas** — *Pirmasis skyrius — dešinėje. Antrasis — kairėje.*',
            '4. **Aprūpinimas** — *Aprūpinimas atvyks rytą.*',
            '5. **Ryšys** — *Šaukinys Vilkas vienas, dažnis atsarginis.*',
            '',
            'Then confirm: **Aišku? Klausimai?** — Clear? Questions?',
          ].join('\n'),
        },
        drills: [
          { lt: 'Mūsų užduotis — stebėti kelią.', en: 'Our mission is to observe the road.' },
          { lt: 'Tikslas — užimti kalvą.', en: 'The objective is to seize the hill.' },
          { lt: 'Judame mano signalu.', en: 'We move on my signal.' },
          { lt: 'Įsakau užimti poziciją.', en: 'I order you to occupy the position.' },
          { lt: 'Užduotis įvykdyta.', en: 'The mission is complete.' },
        ],
        xp: 40,
      },
      {
        slug: 'pozicijos',
        title: 'Pozicijos',
        subtitle: 'Occupy, dig in, arcs of fire',
        emoji: '🕳️',
        words: ['užimti', 'pozicija', 'apkasas', 'sektorius'],
        drills: [
          { lt: 'Užimkite pozicijas!', en: 'Occupy your positions!' },
          { lt: 'Kaskite apkasus.', en: 'Dig fighting positions.' },
          {
            lt: 'Tavo sektorius — nuo medžio iki kelio.',
            en: 'Your arc is from the tree to the road.',
          },
          { lt: 'Pozicija užimta.', en: 'The position is occupied.' },
        ],
        xp: 35,
      },
      {
        slug: 'komandos-darbas',
        title: 'Komandos darbas',
        subtitle: 'Ready? Moving. Checked. Done.',
        emoji: '🤝',
        words: ['Pasiruošę?', 'Judam!', 'po vieną', 'kartu', 'Patikrinta', 'Įvykdyta'],
        drills: [
          { lt: 'Pasiruošę? Judam!', en: 'Ready? Let’s move!' },
          { lt: 'Kertame kelią po vieną.', en: 'We cross the road one at a time.' },
          { lt: 'Ginklai patikrinti.', en: 'Weapons checked.' },
          { lt: 'Užduotis įvykdyta, grįžtame.', en: 'Task complete, we are returning.' },
        ],
        xp: 35,
      },
    ],
  },
];
